// [单词, 音标, 中文, 例句, 例句翻译]
const WORDS = [
["hello","/həˈloʊ/","int. 你好","Hello, nice to meet you.","你好，很高兴认识你。"],
["thanks","/θæŋks/","int. 谢谢","Thanks for your help.","谢谢你的帮助。"],
["sorry","/ˈsɑːri/","adj. 抱歉的","Sorry, I'm late.","抱歉，我迟到了。"],
["please","/pliːz/","adv. 请","Please sit down.","请坐。"],
["yes","/jes/","adv. 是的","Yes, I can.","是的，我可以。"],
["name","/neɪm/","n. 名字","What's your name?","你叫什么名字？"],
["friend","/frend/","n. 朋友","She is my best friend.","她是我最好的朋友。"],
["family","/ˈfæməli/","n. 家庭；家人","I love my family.","我爱我的家人。"],
["mother","/ˈmʌðər/","n. 母亲","My mother is a teacher.","我妈妈是老师。"],
["father","/ˈfɑːðər/","n. 父亲","My father works in a bank.","我爸爸在银行工作。"],
["child","/tʃaɪld/","n. 孩子","The child is sleeping.","孩子在睡觉。"],
["people","/ˈpiːpl/","n. 人们","Many people like coffee.","很多人喜欢咖啡。"],
["man","/mæn/","n. 男人","That man is very tall.","那个男人很高。"],
["woman","/ˈwʊmən/","n. 女人","The woman is my boss.","那位女士是我的老板。"],
["home","/hoʊm/","n. 家 adv. 回家","I want to go home.","我想回家。"],
["house","/haʊs/","n. 房子","They live in a big house.","他们住在一栋大房子里。"],
["room","/ruːm/","n. 房间","My room is small.","我的房间很小。"],
["door","/dɔːr/","n. 门","Please close the door.","请关门。"],
["window","/ˈwɪndoʊ/","n. 窗户","Can you open the window?","你能打开窗户吗？"],
["table","/ˈteɪbl/","n. 桌子","The keys are on the table.","钥匙在桌子上。"],
["bed","/bed/","n. 床","I go to bed at eleven.","我十一点睡觉。"],
["water","/ˈwɔːtər/","n. 水","Can I have some water?","能给我一些水吗？"],
["food","/fuːd/","n. 食物","The food here is good.","这里的东西很好吃。"],
["rice","/raɪs/","n. 米饭","I eat rice every day.","我每天吃米饭。"],
["bread","/bred/","n. 面包","I have bread for breakfast.","我早餐吃面包。"],
["egg","/eɡ/","n. 鸡蛋","I'd like two eggs, please.","请给我两个鸡蛋。"],
["milk","/mɪlk/","n. 牛奶","Do you want some milk?","你想喝点牛奶吗？"],
["coffee","/ˈkɔːfi/","n. 咖啡","I need a cup of coffee.","我需要一杯咖啡。"],
["tea","/tiː/","n. 茶","Would you like some tea?","你想喝点茶吗？"],
["fruit","/fruːt/","n. 水果","Fruit is good for you.","水果对你有好处。"],
["apple","/ˈæpl/","n. 苹果","An apple a day keeps the doctor away.","一天一苹果，医生远离我。"],
["breakfast","/ˈbrekfəst/","n. 早餐","Did you have breakfast?","你吃早餐了吗？"],
["lunch","/lʌntʃ/","n. 午餐","Let's have lunch together.","我们一起吃午饭吧。"],
["dinner","/ˈdɪnər/","n. 晚餐","Dinner is ready.","晚饭好了。"],
["hungry","/ˈhʌŋɡri/","adj. 饿的","I'm so hungry.","我好饿。"],
["thirsty","/ˈθɜːrsti/","adj. 渴的","Are you thirsty?","你渴吗？"],
["eat","/iːt/","v. 吃","What do you want to eat?","你想吃什么？"],
["drink","/drɪŋk/","v. 喝","I drink water every morning.","我每天早上喝水。"],
["cook","/kʊk/","v. 做饭","Can you cook?","你会做饭吗？"],
["buy","/baɪ/","v. 买","I want to buy a new phone.","我想买一部新手机。"],
["pay","/peɪ/","v. 付钱","Can I pay by card?","我可以刷卡吗？"],
["money","/ˈmʌni/","n. 钱","I don't have much money.","我没有多少钱。"],
["price","/praɪs/","n. 价格","What's the price of this?","这个多少钱？"],
["cheap","/tʃiːp/","adj. 便宜的","This shirt is cheap.","这件衬衫很便宜。"],
["expensive","/ɪkˈspensɪv/","adj. 贵的","It's too expensive.","太贵了。"],
["shop","/ʃɑːp/","n. 商店","The shop opens at nine.","商店九点开门。"],
["time","/taɪm/","n. 时间","What time is it?","现在几点？"],
["day","/deɪ/","n. 天","Have a nice day!","祝你今天愉快！"],
["today","/təˈdeɪ/","adv. 今天","I'm busy today.","我今天很忙。"],
["tomorrow","/təˈmɑːroʊ/","adv. 明天","See you tomorrow.","明天见。"],
["yesterday","/ˈjestərdeɪ/","adv. 昨天","I saw him yesterday.","我昨天见到他了。"],
["morning","/ˈmɔːrnɪŋ/","n. 早上","Good morning!","早上好！"],
["night","/naɪt/","n. 夜晚","Good night.","晚安。"],
["week","/wiːk/","n. 周","I work five days a week.","我一周工作五天。"],
["year","/jɪr/","n. 年","Happy New Year!","新年快乐！"],
["now","/naʊ/","adv. 现在","I'm coming now.","我现在就来。"],
["later","/ˈleɪtər/","adv. 稍后","Talk to you later.","回头再聊。"],
["early","/ˈɜːrli/","adj./adv. 早","I get up early.","我起得很早。"],
["late","/leɪt/","adj. 晚的；迟的","Don't be late.","别迟到。"],
["work","/wɜːrk/","v./n. 工作","I go to work by bus.","我坐公交上班。"],
["job","/dʒɑːb/","n. 工作；职业","I like my job.","我喜欢我的工作。"],
["office","/ˈɔːfɪs/","n. 办公室","He is in the office.","他在办公室。"],
["meeting","/ˈmiːtɪŋ/","n. 会议","I have a meeting at ten.","我十点有个会。"],
["busy","/ˈbɪzi/","adj. 忙的","Are you busy now?","你现在忙吗？"],
["free","/friː/","adj. 空闲的；免费的","Are you free tonight?","你今晚有空吗？"],
["school","/skuːl/","n. 学校","My son goes to school.","我儿子在上学。"],
["teacher","/ˈtiːtʃər/","n. 老师","Our teacher is very kind.","我们的老师很和蔼。"],
["student","/ˈstuːdnt/","n. 学生","I am a student.","我是学生。"],
["learn","/lɜːrn/","v. 学习","I want to learn English.","我想学英语。"],
["study","/ˈstʌdi/","v. 学习；研究","I study every evening.","我每天晚上学习。"],
["book","/bʊk/","n. 书","This book is interesting.","这本书很有趣。"],
["read","/riːd/","v. 读","I read before bed.","我睡前看书。"],
["write","/raɪt/","v. 写","Please write your name here.","请在这里写你的名字。"],
["speak","/spiːk/","v. 说（语言）","Do you speak English?","你会说英语吗？"],
["say","/seɪ/","v. 说","What did you say?","你说什么？"],
["tell","/tel/","v. 告诉","Can you tell me the way?","你能告诉我怎么走吗？"],
["talk","/tɔːk/","v. 谈话","Can we talk?","我们能谈谈吗？"],
["ask","/æsk/","v. 问","Can I ask a question?","我可以问个问题吗？"],
["answer","/ˈænsər/","n./v. 回答","I don't know the answer.","我不知道答案。"],
["understand","/ˌʌndərˈstænd/","v. 理解","I don't understand.","我不明白。"],
["know","/noʊ/","v. 知道","I know what you mean.","我知道你的意思。"],
["think","/θɪŋk/","v. 想；认为","I think so.","我也这么认为。"],
["want","/wɑːnt/","v. 想要","I want a cup of tea.","我想要一杯茶。"],
["need","/niːd/","v. 需要","I need your help.","我需要你的帮助。"],
["like","/laɪk/","v. 喜欢","I like music.","我喜欢音乐。"],
["love","/lʌv/","v. 爱","I love this city.","我爱这座城市。"],
["help","/help/","v./n. 帮助","Can you help me?","你能帮我吗？"],
["go","/ɡoʊ/","v. 去","Let's go!","我们走吧！"],
["come","/kʌm/","v. 来","Come here, please.","请过来。"],
["get","/ɡet/","v. 得到；到达","When did you get here?","你什么时候到的？"],
["make","/meɪk/","v. 做；制作","I'll make some tea.","我去泡点茶。"],
["take","/teɪk/","v. 拿；乘坐","I take the subway to work.","我坐地铁上班。"],
["give","/ɡɪv/","v. 给","Please give me a minute.","请给我一分钟。"],
["see","/siː/","v. 看见","Nice to see you again.","很高兴再次见到你。"],
["look","/lʊk/","v. 看","Look at this photo.","看看这张照片。"],
["watch","/wɑːtʃ/","v. 观看","I watch TV at night.","我晚上看电视。"],
["listen","/ˈlɪsn/","v. 听","Listen to me, please.","请听我说。"],
["hear","/hɪr/","v. 听见","Can you hear me?","你能听到我说话吗？"],
["feel","/fiːl/","v. 感觉","I feel tired.","我觉得累。"],
["try","/traɪ/","v. 尝试","Let me try again.","让我再试一次。"],
["wait","/weɪt/","v. 等待","Please wait a moment.","请稍等。"],
["stop","/stɑːp/","v. 停止","Please stop here.","请在这里停。"],
["open","/ˈoʊpən/","v. 打开","What time do you open?","你们几点开门？"],
["close","/kloʊz/","v. 关闭","Please close the window.","请关上窗户。"],
["call","/kɔːl/","v. 打电话","I'll call you later.","我晚点给你打电话。"],
["phone","/foʊn/","n. 手机；电话","My phone is dead.","我手机没电了。"],
["car","/kɑːr/","n. 汽车","I drive my car to work.","我开车上班。"],
["bus","/bʌs/","n. 公交车","Where is the bus stop?","公交车站在哪里？"],
["train","/treɪn/","n. 火车","The train is late.","火车晚点了。"],
["airport","/ˈerpɔːrt/","n. 机场","How do I get to the airport?","我怎么去机场？"],
["hotel","/hoʊˈtel/","n. 酒店","I booked a hotel room.","我订了一间酒店房间。"],
["ticket","/ˈtɪkɪt/","n. 票","One ticket, please.","请给我一张票。"],
["street","/striːt/","n. 街道","This street is very busy.","这条街很热闹。"],
["left","/left/","n./adv. 左边","Turn left here.","在这里左转。"],
["right","/raɪt/","adj. 右边的；正确的","You are right.","你说得对。"],
["near","/nɪr/","prep./adj. 在附近","Is there a bank near here?","这附近有银行吗？"],
["far","/fɑːr/","adj. 远的","Is it far from here?","离这里远吗？"],
["here","/hɪr/","adv. 这里","I'm here.","我在这儿。"],
["there","/ðer/","adv. 那里","Put it over there.","把它放在那边。"],
["weather","/ˈweðər/","n. 天气","The weather is nice today.","今天天气很好。"],
["hot","/hɑːt/","adj. 热的","It's very hot today.","今天很热。"],
["cold","/koʊld/","adj. 冷的","I'm cold.","我冷。"],
["rain","/reɪn/","n. 雨 v. 下雨","It might rain tomorrow.","明天可能会下雨。"],
["good","/ɡʊd/","adj. 好的","That's a good idea.","那是个好主意。"],
["bad","/bæd/","adj. 坏的；严重的","I have a bad cold.","我得了重感冒。"],
["big","/bɪɡ/","adj. 大的","This box is too big.","这个箱子太大了。"],
["small","/smɔːl/","adj. 小的","Do you have a small size?","有小号吗？"],
["new","/nuː/","adj. 新的","I have a new job.","我有了一份新工作。"],
["old","/oʊld/","adj. 旧的；老的","How old are you?","你多大了？"],
["happy","/ˈhæpi/","adj. 开心的","I'm happy to help.","我很乐意帮忙。"],
["sad","/sæd/","adj. 难过的","Why are you sad?","你为什么难过？"],
["tired","/ˈtaɪərd/","adj. 累的","I'm tired after work.","下班后我很累。"],
["easy","/ˈiːzi/","adj. 容易的","This is easy.","这很简单。"],
["difficult","/ˈdɪfɪkəlt/","adj. 困难的","English is not difficult.","英语并不难。"],
["beautiful","/ˈbjuːtɪfl/","adj. 美丽的","What a beautiful day!","多美好的一天！"],
["sick","/sɪk/","adj. 生病的","I feel sick.","我感觉不舒服。"],
["doctor","/ˈdɑːktər/","n. 医生","You should see a doctor.","你应该去看医生。"],
["hospital","/ˈhɑːspɪtl/","n. 医院","Where is the hospital?","医院在哪里？"],
["again","/əˈɡen/","adv. 再一次","Could you say that again?","你能再说一遍吗？"],
["slowly","/ˈsloʊli/","adv. 慢慢地","Please speak slowly.","请说慢一点。"],
["maybe","/ˈmeɪbi/","adv. 也许","Maybe next time.","也许下次吧。"],
["really","/ˈriːəli/","adv. 真的","Really? I didn't know that.","真的吗？我不知道。"],
["very","/ˈveri/","adv. 非常","Thank you very much.","非常感谢。"],
["always","/ˈɔːlweɪz/","adv. 总是","I always get up at seven.","我总是七点起床。"],
["never","/ˈnevər/","adv. 从不","I never drink coffee at night.","我晚上从不喝咖啡。"],
["together","/təˈɡeðər/","adv. 一起","Let's go together.","我们一起去吧。"],
["weekend","/ˈwiːkend/","n. 周末","What did you do on the weekend?","你周末做了什么？"],
["movie","/ˈmuːvi/","n. 电影","Let's watch a movie.","我们看部电影吧。"],
["music","/ˈmjuːzɪk/","n. 音乐","What music do you like?","你喜欢什么音乐？"],
["photo","/ˈfoʊtoʊ/","n. 照片","Can you take a photo of us?","你能帮我们拍张照吗？"],
];

// [英文句子, 中文]
const PHRASES = [
["How are you?","你好吗？"],
["I'm fine, thank you. And you?","我很好，谢谢。你呢？"],
["Nice to meet you.","很高兴认识你。"],
["Where are you from?","你来自哪里？"],
["I'm from China.","我来自中国。"],
["What do you do?","你是做什么工作的？"],
["I'm learning English.","我在学英语。"],
["Excuse me, where is the restroom?","打扰一下，洗手间在哪里？"],
["Could you help me, please?","你能帮我一下吗？"],
["I'm sorry, I don't understand.","抱歉，我不明白。"],
["Could you speak more slowly?","你能说慢一点吗？"],
["Pardon?","请再说一遍？"],
["What does this mean?","这是什么意思？"],
["How do you say this in English?","这个用英语怎么说？"],
["How much is it?","这个多少钱？"],
["I'm just looking, thanks.","我只是看看，谢谢。"],
["Do you have this in a bigger size?","这个有大一号的吗？"],
["Can I try it on?","我可以试穿吗？"],
["I'll take it.","我买了。"],
["Can I have the bill, please?","请给我账单。"],
["I'd like a coffee, please.","我想要一杯咖啡。"],
["A table for two, please.","请给我们一张两人桌。"],
["Can I see the menu?","我能看一下菜单吗？"],
["This is delicious.","这个很好吃。"],
["I'm full.","我吃饱了。"],
["I'm allergic to peanuts.","我对花生过敏。"],
["How do I get to the station?","我怎么去车站？"],
["It's about ten minutes on foot.","走路大约十分钟。"],
["I'm looking for this address.","我在找这个地址。"],
["I have a reservation.","我有预订。"],
["What's the Wi-Fi password?","Wi-Fi 密码是多少？"],
["My phone is out of battery.","我的手机没电了。"],
["What time does it start?","几点开始？"],
["Let's meet at six.","我们六点见吧。"],
["I'm on my way.","我在路上了。"],
["Sorry to keep you waiting.","抱歉让你久等了。"],
["Sounds good.","听起来不错。"],
["No problem.","没问题。"],
["Don't worry.","别担心。"],
["Take your time.","慢慢来，不着急。"],
["You're welcome.","不客气。"],
["It's my pleasure.","我很乐意。"],
["What do you think?","你觉得呢？"],
["I agree with you.","我同意你的看法。"],
["I'm not sure.","我不太确定。"],
["That makes sense.","有道理。"],
["Let me think about it.","让我想一想。"],
["What's the weather like today?","今天天气怎么样？"],
["I don't feel well.","我不太舒服。"],
["Call an ambulance!","快叫救护车！"],
["Have a good weekend!","周末愉快！"],
["See you soon.","回头见。"],
["Take care.","保重。"],
["Practice makes perfect.","熟能生巧。"],
];

const TRAVEL = [
["passport","/ˈpæspɔːrt/","n. 护照","May I see your passport, please?","请出示您的护照。"],
["visa","/ˈviːzə/","n. 签证","I need a visa to visit Japan.","我去日本需要签证。"],
["flight","/flaɪt/","n. 航班","My flight leaves at eight in the morning.","我的航班早上八点起飞。"],
["boarding pass","/ˈbɔːrdɪŋ pæs/","n. 登机牌","Here is your boarding pass.","这是您的登机牌。"],
["gate","/ɡeɪt/","n. 登机口","Our flight boards at Gate 12.","我们的航班在12号登机口登机。"],
["departure","/dɪˈpɑːrtʃər/","n. 出发","Please check the departure time.","请确认出发时间。"],
["arrival","/əˈraɪvl/","n. 到达","The arrival hall is downstairs.","到达大厅在楼下。"],
["delay","/dɪˈleɪ/","n./v. 延误","The flight is delayed by two hours.","航班延误了两个小时。"],
["cancel","/ˈkænsl/","v. 取消","My flight was canceled.","我的航班被取消了。"],
["passenger","/ˈpæsɪndʒər/","n. 乘客","All passengers please board now.","请所有乘客现在登机。"],
["take off","/ˌteɪk ˈɔːf/","v. 起飞","The plane will take off soon.","飞机马上要起飞了。"],
["land","/lænd/","v. 降落","We will land in ten minutes.","我们将在十分钟后降落。"],
["connecting flight","/kəˈnektɪŋ flaɪt/","n. 转机航班","I have a connecting flight in Dubai.","我在迪拜转机。"],
["jet lag","/ˈdʒet læɡ/","n. 时差反应","I still have jet lag.","我还在倒时差。"],
["luggage","/ˈlʌɡɪdʒ/","n. 行李","How many pieces of luggage do you have?","您有几件行李？"],
["suitcase","/ˈsuːtkeɪs/","n. 行李箱","My suitcase is too heavy.","我的行李箱太重了。"],
["backpack","/ˈbækpæk/","n. 双肩包","I only have a backpack.","我只有一个双肩包。"],
["carry-on","/ˈkæri ɑːn/","n. 随身行李","Can I take this as a carry-on?","这个可以作为随身行李吗？"],
["overweight","/ˌoʊvərˈweɪt/","adj. 超重的","Your bag is overweight.","您的行李超重了。"],
["aisle","/aɪl/","n. 过道","I'd like an aisle seat.","我想要靠过道的座位。"],
["window seat","/ˈwɪndoʊ siːt/","n. 靠窗座位","Can I have a window seat?","我可以要靠窗的座位吗？"],
["seat","/siːt/","n. 座位","Is this seat taken?","这个座位有人吗？"],
["customs","/ˈkʌstəmz/","n. 海关","We need to go through customs.","我们需要过海关。"],
["declare","/dɪˈkler/","v. 申报","I have nothing to declare.","我没有需要申报的东西。"],
["security","/səˈkjʊrəti/","n. 安检；安全","Please put your bag through security.","请把包放进安检机。"],
["check in","/ˌtʃek ˈɪn/","v. 办理登机；入住","Where can I check in?","我在哪里办理登机？"],
["check out","/ˌtʃek ˈaʊt/","v. 退房","I'd like to check out, please.","我想退房。"],
["reservation","/ˌrezərˈveɪʃn/","n. 预订","I made a reservation online.","我在网上预订了。"],
["single room","/ˈsɪŋɡl ruːm/","n. 单人间","I'd like a single room for two nights.","我想要一间单人房，住两晚。"],
["double room","/ˈdʌbl ruːm/","n. 双人间","Do you have a double room?","你们有双人间吗？"],
["key card","/ˈkiː kɑːrd/","n. 房卡","My key card doesn't work.","我的房卡不能用了。"],
["reception","/rɪˈsepʃn/","n. 前台","Please leave your key at reception.","请把钥匙留在前台。"],
["lobby","/ˈlɑːbi/","n. 大堂","I'll wait for you in the lobby.","我在大堂等你。"],
["elevator","/ˈelɪveɪtər/","n. 电梯","The elevator is on your right.","电梯在您右边。"],
["towel","/ˈtaʊəl/","n. 毛巾","Could I have an extra towel?","能多给我一条毛巾吗？"],
["room service","/ˈruːm ˌsɜːrvɪs/","n. 客房服务","I'd like to order room service.","我想叫客房服务。"],
["wake-up call","/ˈweɪk ʌp kɔːl/","n. 叫醒服务","Can I have a wake-up call at six?","能六点叫醒我吗？"],
["hostel","/ˈhɑːstl/","n. 青年旅舍","We stayed in a hostel.","我们住在青年旅舍。"],
["Wi-Fi","/ˈwaɪ faɪ/","n. 无线网络","Is there free Wi-Fi here?","这里有免费 Wi-Fi 吗？"],
["map","/mæp/","n. 地图","Can you show me on the map?","你能在地图上指给我看吗？"],
["direction","/dəˈrekʃn/","n. 方向","I think we're going in the wrong direction.","我觉得我们走错方向了。"],
["straight","/streɪt/","adv. 直走","Go straight for two blocks.","直走两个路口。"],
["corner","/ˈkɔːrnər/","n. 拐角","The bank is on the corner.","银行在拐角处。"],
["block","/blɑːk/","n. 街区","It's three blocks away.","离这里三个街区。"],
["intersection","/ˌɪntərˈsekʃn/","n. 十字路口","Turn right at the intersection.","在十字路口右转。"],
["nearby","/ˌnɪrˈbaɪ/","adv. 在附近","Is there a supermarket nearby?","附近有超市吗？"],
["city center","/ˈsɪti ˌsentər/","n. 市中心","How far is the city center?","离市中心有多远？"],
["on foot","/ɑːn ˈfʊt/","步行","We went there on foot.","我们是走路去的。"],
["subway","/ˈsʌbweɪ/","n. 地铁","Is there a subway station near here?","这附近有地铁站吗？"],
["taxi","/ˈtæksi/","n. 出租车","Let's take a taxi.","我们打车吧。"],
["station","/ˈsteɪʃn/","n. 车站","The station is very crowded.","车站很拥挤。"],
["platform","/ˈplætfɔːrm/","n. 站台","The train leaves from Platform 3.","火车从3号站台出发。"],
["one-way","/ˌwʌn ˈweɪ/","adj. 单程的","A one-way ticket to London, please.","请给我一张去伦敦的单程票。"],
["round trip","/ˌraʊnd ˈtrɪp/","n. 往返","How much is a round trip ticket?","往返票多少钱？"],
["ticket office","/ˈtɪkɪt ˌɔːfɪs/","n. 售票处","Where is the ticket office?","售票处在哪里？"],
["ferry","/ˈferi/","n. 渡轮","The ferry leaves every hour.","渡轮每小时一班。"],
["rent","/rent/","v. 租","We want to rent a car.","我们想租一辆车。"],
["driver's license","/ˈdraɪvərz ˌlaɪsns/","n. 驾照","Do you have an international driver's license?","你有国际驾照吗？"],
["gas station","/ˈɡæs ˌsteɪʃn/","n. 加油站","Is there a gas station nearby?","附近有加油站吗？"],
["traffic","/ˈtræfɪk/","n. 交通","The traffic is terrible today.","今天交通很糟糕。"],
["entrance","/ˈentrəns/","n. 入口","The entrance is over there.","入口在那边。"],
["exit","/ˈeksɪt/","n. 出口","Where is the exit?","出口在哪里？"],
["trip","/trɪp/","n. 旅行","How was your trip?","你的旅行怎么样？"],
["journey","/ˈdʒɜːrni/","n. 旅程","Have a safe journey!","一路平安！"],
["vacation","/veɪˈkeɪʃn/","n. 假期","I'm on vacation next week.","我下周休假。"],
["destination","/ˌdestɪˈneɪʃn/","n. 目的地","We will reach our destination soon.","我们很快就到目的地了。"],
["itinerary","/aɪˈtɪnəreri/","n. 行程表","Here is our travel itinerary.","这是我们的行程表。"],
["travel insurance","/ˈtrævl ɪnˌʃʊrəns/","n. 旅行保险","Did you buy travel insurance?","你买旅行保险了吗？"],
["pack","/pæk/","v. 收拾行李","Have you packed yet?","你收拾好行李了吗？"],
["abroad","/əˈbrɔːd/","adv. 在国外","Have you ever traveled abroad?","你出过国吗？"],
["tourist","/ˈtʊrɪst/","n. 游客","This place is full of tourists.","这里到处都是游客。"],
["tour","/tʊr/","n. 观光；参观","We joined a city tour.","我们参加了一个城市观光团。"],
["guide","/ɡaɪd/","n. 导游","Our guide speaks good English.","我们的导游英语很好。"],
["sightseeing","/ˈsaɪtsiːɪŋ/","n. 观光","We went sightseeing all day.","我们观光了一整天。"],
["museum","/mjuˈziːəm/","n. 博物馆","The museum is closed on Mondays.","博物馆周一闭馆。"],
["temple","/ˈtempl/","n. 寺庙","This temple is 500 years old.","这座寺庙有500年历史了。"],
["park","/pɑːrk/","n. 公园","Let's take a walk in the park.","我们去公园散步吧。"],
["beach","/biːtʃ/","n. 海滩","Let's go to the beach.","我们去海滩吧。"],
["island","/ˈaɪlənd/","n. 岛","We took a boat to the island.","我们坐船去了岛上。"],
["mountain","/ˈmaʊntn/","n. 山","We climbed the mountain yesterday.","我们昨天爬了山。"],
["view","/vjuː/","n. 景色","The view is amazing.","景色太美了。"],
["local","/ˈloʊkl/","adj. 当地的","I want to try some local food.","我想尝尝当地美食。"],
["foreign","/ˈfɔːrən/","adj. 外国的","Do you accept foreign cards?","你们收外国银行卡吗？"],
["exchange","/ɪksˈtʃeɪndʒ/","v. 兑换","Where can I exchange money?","我在哪里可以换钱？"],
["souvenir","/ˌsuːvəˈnɪr/","n. 纪念品","I bought some souvenirs for my friends.","我给朋友买了些纪念品。"],
["camera","/ˈkæmərə/","n. 相机","I left my camera in the hotel.","我把相机落在酒店了。"],
["charger","/ˈtʃɑːrdʒər/","n. 充电器","Can I borrow your charger?","我能借用你的充电器吗？"],
["adapter","/əˈdæptər/","n. 转换插头","I need a power adapter.","我需要一个电源转换插头。"],
["sunscreen","/ˈsʌnskriːn/","n. 防晒霜","Don't forget your sunscreen.","别忘了防晒霜。"],
["umbrella","/ʌmˈbrelə/","n. 雨伞","Take an umbrella with you.","带上雨伞。"],
["lost","/lɔːst/","adj. 迷路的；丢失的","I think I'm lost.","我好像迷路了。"],
["lost and found","/ˌlɔːst ən ˈfaʊnd/","n. 失物招领处","Let's ask at the lost and found.","我们去失物招领处问问。"],
["police","/pəˈliːs/","n. 警察","Please call the police.","请报警。"],
["embassy","/ˈembəsi/","n. 大使馆","Where is the Chinese Embassy?","中国大使馆在哪里？"],
];

const BUSINESS = [
["company","/ˈkʌmpəni/","n. 公司","I work for a trading company.","我在一家贸易公司工作。"],
["business","/ˈbɪznəs/","n. 生意；商业","How's business?","生意怎么样？"],
["customer","/ˈkʌstəmər/","n. 顾客","The customer is always right.","顾客永远是对的。"],
["client","/ˈklaɪənt/","n. 客户","I'm meeting a client this afternoon.","我今天下午要见一个客户。"],
["manager","/ˈmænɪdʒər/","n. 经理","I'd like to speak to the manager.","我想和经理谈谈。"],
["boss","/bɔːs/","n. 老板","My boss is on a business trip.","我老板在出差。"],
["colleague","/ˈkɑːliːɡ/","n. 同事","She is my colleague.","她是我同事。"],
["team","/tiːm/","n. 团队","Our team works very hard.","我们团队非常努力。"],
["department","/dɪˈpɑːrtmənt/","n. 部门","Which department do you work in?","你在哪个部门工作？"],
["headquarters","/ˈhedkwɔːrtərz/","n. 总部","Our headquarters is in Shenzhen.","我们的总部在深圳。"],
["partner","/ˈpɑːrtnər/","n. 合作伙伴","They are our business partners.","他们是我们的生意伙伴。"],
["cooperation","/koʊˌɑːpəˈreɪʃn/","n. 合作","We look forward to our cooperation.","我们期待与您合作。"],
["supplier","/səˈplaɪər/","n. 供应商","We need a new supplier.","我们需要一个新的供应商。"],
["competitor","/kəmˈpetɪtər/","n. 竞争对手","Our competitor lowered their prices.","我们的竞争对手降价了。"],
["product","/ˈprɑːdʌkt/","n. 产品","This is our new product.","这是我们的新产品。"],
["service","/ˈsɜːrvɪs/","n. 服务","We offer the best service.","我们提供最好的服务。"],
["brand","/brænd/","n. 品牌","This is a famous brand.","这是个知名品牌。"],
["quality","/ˈkwɑːləti/","n. 质量","We care about quality.","我们重视质量。"],
["quantity","/ˈkwɑːntəti/","n. 数量","What is the minimum quantity?","最小数量是多少？"],
["sample","/ˈsæmpl/","n. 样品","Could you send us a sample?","能给我们寄个样品吗？"],
["order","/ˈɔːrdər/","n. 订单","We received a big order.","我们收到一个大订单。"],
["quote","/kwoʊt/","n. 报价","Can you give me a quote?","能给我一个报价吗？"],
["discount","/ˈdɪskaʊnt/","n. 折扣","Can you give us a discount?","能给我们打个折吗？"],
["offer","/ˈɔːfər/","n. 报价；提议","That's a good offer.","这是个不错的报价。"],
["negotiate","/nɪˈɡoʊʃieɪt/","v. 谈判","We need to negotiate the price.","我们需要谈一下价格。"],
["deal","/diːl/","n. 交易","It's a deal!","成交！"],
["contract","/ˈkɑːntrækt/","n. 合同","Please sign the contract.","请签合同。"],
["sign","/saɪn/","v. 签字","Where do I sign?","我在哪里签字？"],
["agreement","/əˈɡriːmənt/","n. 协议","We reached an agreement.","我们达成了协议。"],
["deliver","/dɪˈlɪvər/","v. 交付；送货","We can deliver next week.","我们下周可以交货。"],
["delivery","/dɪˈlɪvəri/","n. 交货","When is the delivery date?","交货日期是什么时候？"],
["shipment","/ˈʃɪpmənt/","n. 一批货","The shipment will arrive next Monday.","这批货下周一到。"],
["logistics","/ləˈdʒɪstɪks/","n. 物流","Who handles the logistics?","谁负责物流？"],
["warehouse","/ˈwerhaʊs/","n. 仓库","The goods are in the warehouse.","货物在仓库里。"],
["factory","/ˈfæktəri/","n. 工厂","Would you like to visit our factory?","您想参观我们的工厂吗？"],
["stock","/stɑːk/","n. 库存","This item is out of stock.","这件商品缺货了。"],
["export","/ˈekspɔːrt/","n./v. 出口","We export to Europe.","我们出口到欧洲。"],
["import","/ˈɪmpɔːrt/","n./v. 进口","We import machines from Germany.","我们从德国进口机器。"],
["launch","/lɔːntʃ/","v. 推出","We will launch the product in May.","我们将在五月推出这款产品。"],
["market","/ˈmɑːrkɪt/","n. 市场","The market is growing fast.","市场增长很快。"],
["marketing","/ˈmɑːrkɪtɪŋ/","n. 市场营销","I work in marketing.","我做市场营销。"],
["sales","/seɪlz/","n. 销售；销售额","Our sales went up this month.","这个月我们的销售额上升了。"],
["target","/ˈtɑːrɡɪt/","n. 目标","We met our sales target.","我们完成了销售目标。"],
["strategy","/ˈstrætədʒi/","n. 策略","We need a new strategy.","我们需要一个新策略。"],
["advantage","/ədˈvæntɪdʒ/","n. 优势","What's our main advantage?","我们的主要优势是什么？"],
["project","/ˈprɑːdʒekt/","n. 项目","The project is almost finished.","项目快完成了。"],
["plan","/plæn/","n. 计划","What's the plan for today?","今天的计划是什么？"],
["goal","/ɡoʊl/","n. 目标","Our goal is to double sales.","我们的目标是销售额翻倍。"],
["progress","/ˈprɑːɡres/","n. 进展","We're making good progress.","我们进展顺利。"],
["deadline","/ˈdedlaɪn/","n. 截止日期","The deadline is Friday.","截止日期是周五。"],
["urgent","/ˈɜːrdʒənt/","adj. 紧急的","This is urgent.","这件事很紧急。"],
["schedule","/ˈskedʒuːl/","n. 日程","Let me check my schedule.","我查一下我的日程。"],
["appointment","/əˈpɔɪntmənt/","n. 预约","I have an appointment at three.","我三点有个预约。"],
["available","/əˈveɪləbl/","adj. 有空的","Are you available on Monday?","你周一有空吗？"],
["reschedule","/ˌriːˈskedʒuːl/","v. 改期","Can we reschedule the meeting?","我们能把会议改期吗？"],
["postpone","/poʊˈspoʊn/","v. 推迟","The meeting is postponed.","会议推迟了。"],
["conference","/ˈkɑːnfərəns/","n. 会议；大会","I'm going to a conference in Shanghai.","我要去上海参加一个会议。"],
["agenda","/əˈdʒendə/","n. 议程","What's on the agenda today?","今天的议程是什么？"],
["presentation","/ˌpriːzenˈteɪʃn/","n. 演示；汇报","I have a presentation tomorrow.","我明天要做汇报。"],
["proposal","/prəˈpoʊzl/","n. 方案；提案","I'll send you the proposal today.","我今天把方案发给你。"],
["report","/rɪˈpɔːrt/","n. 报告","Please finish the report by Monday.","请在周一前完成报告。"],
["discuss","/dɪˈskʌs/","v. 讨论","Let's discuss it tomorrow.","我们明天讨论吧。"],
["decide","/dɪˈsaɪd/","v. 决定","We need to decide today.","我们今天需要做决定。"],
["decision","/dɪˈsɪʒn/","n. 决定","That's a good decision.","这是个好决定。"],
["problem","/ˈprɑːbləm/","n. 问题","We have a small problem.","我们有个小问题。"],
["solution","/səˈluːʃn/","n. 解决方案","Let's find a solution.","我们找个解决办法吧。"],
["suggest","/səɡˈdʒest/","v. 建议","What do you suggest?","你有什么建议？"],
["idea","/aɪˈdiːə/","n. 主意","I have an idea.","我有个主意。"],
["opinion","/əˈpɪnjən/","n. 意见","What's your opinion?","你的意见是什么？"],
["feedback","/ˈfiːdbæk/","n. 反馈","Thanks for your feedback.","谢谢你的反馈。"],
["complaint","/kəmˈpleɪnt/","n. 投诉","We received a complaint.","我们收到了一个投诉。"],
["email","/ˈiːmeɪl/","n. 电子邮件","I'll send you an email.","我会给你发邮件。"],
["reply","/rɪˈplaɪ/","v./n. 回复","Thanks for your quick reply.","谢谢你的快速回复。"],
["attach","/əˈtætʃ/","v. 附上","I've attached the file.","我已附上文件。"],
["file","/faɪl/","n. 文件","Can you send me the file?","你能把文件发给我吗？"],
["document","/ˈdɑːkjumənt/","n. 文件","Please read this document.","请看一下这份文件。"],
["update","/ˈʌpdeɪt/","n. 最新情况","Any update on the order?","订单有什么新进展吗？"],
["confirm","/kənˈfɜːrm/","v. 确认","Please confirm the meeting time.","请确认会议时间。"],
["follow up","/ˌfɑːloʊ ˈʌp/","v. 跟进","I'll follow up with the client.","我会跟进这个客户。"],
["contact","/ˈkɑːntækt/","v./n. 联系","Please contact me anytime.","请随时联系我。"],
["introduce","/ˌɪntrəˈduːs/","v. 介绍","Let me introduce myself.","我来自我介绍一下。"],
["business card","/ˈbɪznəs kɑːrd/","n. 名片","Here's my business card.","这是我的名片。"],
["business trip","/ˈbɪznəs trɪp/","n. 出差","I'm going on a business trip next week.","我下周要出差。"],
["successful","/səkˈsesfl/","adj. 成功的","The meeting was successful.","会议很成功。"],
["responsible","/rɪˈspɑːnsəbl/","adj. 负责的","I'm responsible for sales.","我负责销售。"],
["experience","/ɪkˈspɪriəns/","n. 经验","I have five years of experience.","我有五年工作经验。"],
["skill","/skɪl/","n. 技能","Communication is an important skill.","沟通是一项重要的技能。"],
["interview","/ˈɪntərvjuː/","n. 面试","I have a job interview tomorrow.","我明天有个面试。"],
["resume","/ˈrezəmeɪ/","n. 简历","Please send me your resume.","请把你的简历发给我。"],
["hire","/ˈhaɪər/","v. 雇用","We plan to hire two new people.","我们打算招两个新人。"],
["promotion","/prəˈmoʊʃn/","n. 升职","Congratulations on your promotion!","恭喜你升职！"],
];

const FINANCE = [
["finance","/ˈfaɪnæns/","n. 财务；金融","She works in finance.","她在财务部门工作。"],
["accounting","/əˈkaʊntɪŋ/","n. 会计","I studied accounting at university.","我大学学的是会计。"],
["accountant","/əˈkaʊntənt/","n. 会计师","Our accountant will check the numbers.","我们的会计会核对数字。"],
["bookkeeping","/ˈbʊkkiːpɪŋ/","n. 记账","She does the bookkeeping for small companies.","她给小公司做记账。"],
["bank","/bæŋk/","n. 银行","I need to go to the bank.","我得去趟银行。"],
["account","/əˈkaʊnt/","n. 账户","I want to open a bank account.","我想开一个银行账户。"],
["balance","/ˈbæləns/","n. 余额","What's my account balance?","我的账户余额是多少？"],
["deposit","/dɪˈpɑːzɪt/","n./v. 存款；押金","I'd like to deposit some money.","我想存些钱。"],
["withdraw","/wɪðˈdrɔː/","v. 取款","I want to withdraw five hundred dollars.","我想取五百美元。"],
["transfer","/ˈtrænsfɜːr/","n./v. 转账","I'll transfer the money today.","我今天转账。"],
["wire transfer","/ˈwaɪər ˌtrænsfɜːr/","n. 电汇","We paid by wire transfer.","我们用电汇付的款。"],
["cash","/kæʃ/","n. 现金","Do you take cash?","你们收现金吗？"],
["credit card","/ˈkredɪt kɑːrd/","n. 信用卡","Can I pay with a credit card?","我可以用信用卡付款吗？"],
["credit","/ˈkredɪt/","n. 信用；赊账","Can we buy on credit?","我们能赊账吗？"],
["credit limit","/ˈkredɪt ˌlɪmɪt/","n. 信用额度","The customer has reached the credit limit.","该客户已达到信用额度。"],
["currency","/ˈkɜːrənsi/","n. 货币","What currency do they use in Thailand?","泰国用什么货币？"],
["exchange rate","/ɪksˈtʃeɪndʒ reɪt/","n. 汇率","What's today's exchange rate?","今天的汇率是多少？"],
["interest","/ˈɪntrəst/","n. 利息","The bank pays very low interest.","银行利息很低。"],
["interest rate","/ˈɪntrəst reɪt/","n. 利率","Interest rates went up again.","利率又上涨了。"],
["loan","/loʊn/","n. 贷款","We need a bank loan.","我们需要一笔银行贷款。"],
["debt","/det/","n. 债务","The company has no debt.","公司没有负债。"],
["installment","/ɪnˈstɔːlmənt/","n. 分期付款","Can I pay in installments?","我可以分期付款吗？"],
["income","/ˈɪnkʌm/","n. 收入","Our income is stable.","我们的收入很稳定。"],
["salary","/ˈsæləri/","n. 工资","When do we get our salary?","我们什么时候发工资？"],
["bonus","/ˈboʊnəs/","n. 奖金","Everyone got a bonus this year.","今年每个人都拿到了奖金。"],
["earn","/ɜːrn/","v. 挣钱","She earns a good salary.","她工资很高。"],
["save","/seɪv/","v. 存钱；节省","I save money every month.","我每个月都存钱。"],
["spend","/spend/","v. 花费","How much did you spend?","你花了多少钱？"],
["afford","/əˈfɔːrd/","v. 负担得起","I can't afford it.","我买不起。"],
["cost","/kɔːst/","n. 成本；费用","We need to cut costs.","我们需要削减成本。"],
["expense","/ɪkˈspens/","n. 开支","Please keep a record of your expenses.","请记录好你的开支。"],
["budget","/ˈbʌdʒɪt/","n. 预算","We are over budget.","我们超预算了。"],
["profit","/ˈprɑːfɪt/","n. 利润","Our profit increased this year.","今年我们的利润增加了。"],
["loss","/lɔːs/","n. 亏损","The company made a loss last year.","公司去年亏损了。"],
["revenue","/ˈrevənuː/","n. 营收","Our revenue grew by twenty percent.","我们的营收增长了百分之二十。"],
["gross","/ɡroʊs/","adj. 总的；毛的","What's the gross profit?","毛利润是多少？"],
["net","/net/","adj. 净的","Net income was higher than expected.","净收入高于预期。"],
["tax","/tæks/","n. 税","Is tax included?","含税吗？"],
["invoice","/ˈɪnvɔɪs/","n. 发票","Please send us the invoice.","请把发票发给我们。"],
["receipt","/rɪˈsiːt/","n. 收据","Can I have a receipt, please?","能给我一张收据吗？"],
["bill","/bɪl/","n. 账单","I need to pay the electricity bill.","我需要交电费。"],
["payment","/ˈpeɪmənt/","n. 付款","We received your payment.","我们收到了您的付款。"],
["due date","/ˈduː deɪt/","n. 到期日","The due date is next Friday.","到期日是下周五。"],
["overdue","/ˌoʊvərˈduː/","adj. 逾期的","This invoice is overdue.","这张发票已经逾期了。"],
["refund","/ˈriːfʌnd/","n. 退款","I'd like a refund.","我想退款。"],
["fee","/fiː/","n. 费用","Is there a service fee?","有服务费吗？"],
["charge","/tʃɑːrdʒ/","v./n. 收费","How much do you charge?","你们收费多少？"],
["total","/ˈtoʊtl/","n. 总数","What's the total?","总共多少？"],
["amount","/əˈmaʊnt/","n. 金额","Please check the amount.","请核对金额。"],
["figure","/ˈfɪɡjər/","n. 数字","These figures don't look right.","这些数字看起来不对。"],
["percent","/pərˈsent/","n. 百分之…","Sales are up five percent.","销售额增长了百分之五。"],
["average","/ˈævərɪdʒ/","n./adj. 平均","What's the average price?","平均价格是多少？"],
["estimate","/ˈestɪmeɪt/","v. 估算","Can you estimate the cost?","你能估算一下费用吗？"],
["calculate","/ˈkælkjuleɪt/","v. 计算","Let me calculate the total.","我来算一下总数。"],
["increase","/ɪnˈkriːs/","v. 增加","Prices increased last month.","上个月价格上涨了。"],
["decrease","/dɪˈkriːs/","v. 减少","Costs decreased by ten percent.","成本降低了百分之十。"],
["statement","/ˈsteɪtmənt/","n. 对账单","I got my bank statement.","我收到了银行对账单。"],
["financial statement","/faɪˌnænʃl ˈsteɪtmənt/","n. 财务报表","We need to prepare the financial statements.","我们需要准备财务报表。"],
["balance sheet","/ˈbæləns ʃiːt/","n. 资产负债表","Please review the balance sheet.","请审阅资产负债表。"],
["asset","/ˈæset/","n. 资产","Our people are our greatest asset.","员工是我们最大的资产。"],
["liability","/ˌlaɪəˈbɪləti/","n. 负债","Total liabilities are lower this year.","今年总负债更低了。"],
["equity","/ˈekwəti/","n. 股本；权益","They own thirty percent of the equity.","他们拥有百分之三十的股权。"],
["cash flow","/ˈkæʃ floʊ/","n. 现金流","Cash flow is very important.","现金流非常重要。"],
["accounts payable","/əˌkaʊnts ˈpeɪəbl/","n. 应付账款","Accounts payable increased this month.","本月应付账款增加了。"],
["accounts receivable","/əˌkaʊnts rɪˈsiːvəbl/","n. 应收账款","We need to collect accounts receivable.","我们需要催收应收账款。"],
["reconcile","/ˈrekənsaɪl/","v. 对账","We reconcile the accounts every month.","我们每月对账。"],
["depreciation","/dɪˌpriːʃiˈeɪʃn/","n. 折旧","Depreciation reduces the value of assets.","折旧会降低资产价值。"],
["audit","/ˈɔːdɪt/","n. 审计","The audit starts next week.","审计下周开始。"],
["quarter","/ˈkwɔːrtər/","n. 季度","Sales were good this quarter.","本季度销售不错。"],
["annual","/ˈænjuəl/","adj. 年度的","Here is our annual report.","这是我们的年报。"],
["fiscal year","/ˈfɪskl jɪr/","n. 财年","Our fiscal year ends in March.","我们的财年三月结束。"],
["approve","/əˈpruːv/","v. 批准","The manager approved the budget.","经理批准了预算。"],
["reimburse","/ˌriːɪmˈbɜːrs/","v. 报销","The company will reimburse your travel costs.","公司会报销你的差旅费。"],
["reimbursement","/ˌriːɪmˈbɜːrsmənt/","n. 报销","I submitted my reimbursement form.","我交了报销单。"],
["petty cash","/ˌpeti ˈkæʃ/","n. 备用金","We keep some petty cash in the office.","办公室里放了一些备用金。"],
["invest","/ɪnˈvest/","v. 投资","We want to invest in new technology.","我们想投资新技术。"],
["investment","/ɪnˈvestmənt/","n. 投资","It's a good investment.","这是一笔好投资。"],
["investor","/ɪnˈvestər/","n. 投资者","We are looking for investors.","我们在寻找投资者。"],
["share","/ʃer/","n. 股份；股票","He bought shares in the company.","他买了这家公司的股票。"],
["stock market","/ˈstɑːk ˌmɑːrkɪt/","n. 股市","The stock market fell today.","今天股市下跌了。"],
["dividend","/ˈdɪvɪdend/","n. 股息","The company pays a dividend every year.","公司每年派发股息。"],
["fund","/fʌnd/","n. 基金；资金","We don't have enough funds.","我们资金不足。"],
["risk","/rɪsk/","n. 风险","Every investment has risks.","每项投资都有风险。"],
["insurance","/ɪnˈʃʊrəns/","n. 保险","Do you have health insurance?","你有医疗保险吗？"],
["inflation","/ɪnˈfleɪʃn/","n. 通货膨胀","Inflation is rising.","通货膨胀在上升。"],
["economy","/ɪˈkɑːnəmi/","n. 经济","The economy is growing slowly.","经济增长缓慢。"],
];

const DINING = [
["menu","/ˈmenjuː/","n. 菜单","Is the menu in English?","菜单有英文的吗？"],
["waiter","/ˈweɪtər/","n. 服务员","Let's ask the waiter.","我们问问服务员吧。"],
["dish","/dɪʃ/","n. 一道菜","What's your favorite dish?","你最喜欢的菜是什么？"],
["recommend","/ˌrekəˈmend/","v. 推荐","What do you recommend?","你推荐什么？"],
["delicious","/dɪˈlɪʃəs/","adj. 美味的","Everything was delicious.","每样都很好吃。"],
["spicy","/ˈspaɪsi/","adj. 辣的","Is this dish spicy?","这道菜辣吗？"],
["sweet","/swiːt/","adj. 甜的","This cake is too sweet.","这个蛋糕太甜了。"],
["salty","/ˈsɔːlti/","adj. 咸的","The soup is a little salty.","汤有点咸。"],
["sour","/ˈsaʊər/","adj. 酸的","Lemons are sour.","柠檬是酸的。"],
["vegetarian","/ˌvedʒəˈteriən/","n./adj. 素食者","I'm a vegetarian.","我吃素。"],
["chicken","/ˈtʃɪkɪn/","n. 鸡肉","I'll have the chicken.","我要鸡肉。"],
["beef","/biːf/","n. 牛肉","I don't eat beef.","我不吃牛肉。"],
["pork","/pɔːrk/","n. 猪肉","This dish has pork in it.","这道菜里有猪肉。"],
["fish","/fɪʃ/","n. 鱼","The fish is very fresh.","鱼很新鲜。"],
["vegetable","/ˈvedʒtəbl/","n. 蔬菜","Eat more vegetables.","多吃蔬菜。"],
["soup","/suːp/","n. 汤","I'd like a bowl of soup.","我想要一碗汤。"],
["noodles","/ˈnuːdlz/","n. 面条","I love beef noodles.","我爱吃牛肉面。"],
["dessert","/dɪˈzɜːrt/","n. 甜点","Would you like some dessert?","你想来点甜点吗？"],
["juice","/dʒuːs/","n. 果汁","A glass of orange juice, please.","请来一杯橙汁。"],
["beer","/bɪr/","n. 啤酒","Two beers, please.","请来两杯啤酒。"],
["ice","/aɪs/","n. 冰","No ice, please.","请不要加冰。"],
["takeout","/ˈteɪkaʊt/","n. 外卖","Let's get takeout tonight.","我们今晚叫外卖吧。"],
["to go","/tə ˈɡoʊ/","带走","For here or to go?","在这里吃还是带走？"],
["tip","/tɪp/","n. 小费","Is the tip included?","小费包含在内吗？"],
["plate","/pleɪt/","n. 盘子","Could I have another plate?","能再给我一个盘子吗？"],
["fork","/fɔːrk/","n. 叉子","Can I have a fork, please?","能给我一把叉子吗？"],
["knife","/naɪf/","n. 刀","I need a knife.","我需要一把刀。"],
["spoon","/spuːn/","n. 勺子","Can I have a spoon?","能给我一个勺子吗？"],
["chopsticks","/ˈtʃɑːpstɪks/","n. 筷子","Can you use chopsticks?","你会用筷子吗？"],
["napkin","/ˈnæpkɪn/","n. 餐巾纸","Could you pass me a napkin?","能递给我一张餐巾纸吗？"],
["bottle","/ˈbɑːtl/","n. 瓶","A bottle of water, please.","请给我一瓶水。"],
["fresh","/freʃ/","adj. 新鲜的","Are these vegetables fresh?","这些蔬菜新鲜吗？"],
["kilo","/ˈkiːloʊ/","n. 公斤","How much is it per kilo?","一公斤多少钱？"],
["supermarket","/ˈsuːpərmɑːrkɪt/","n. 超市","I'm going to the supermarket.","我要去超市。"],
["mall","/mɔːl/","n. 商场","Let's go shopping at the mall.","我们去商场购物吧。"],
["sale","/seɪl/","n. 促销","Everything is on sale today.","今天所有东西都打折。"],
["size","/saɪz/","n. 尺码","What size do you wear?","你穿什么尺码？"],
["color","/ˈkʌlər/","n. 颜色","Do you have it in another color?","有别的颜色吗？"],
["try on","/ˌtraɪ ˈɑːn/","v. 试穿","Can I try on these shoes?","我能试穿这双鞋吗？"],
["fitting room","/ˈfɪtɪŋ ruːm/","n. 试衣间","Where is the fitting room?","试衣间在哪里？"],
["clothes","/kloʊz/","n. 衣服","I need to buy some new clothes.","我需要买些新衣服。"],
["shirt","/ʃɜːrt/","n. 衬衫","I like this shirt.","我喜欢这件衬衫。"],
["pants","/pænts/","n. 裤子","These pants are too long.","这条裤子太长了。"],
["dress","/dres/","n. 连衣裙","That dress looks great on you.","那条裙子你穿很好看。"],
["jacket","/ˈdʒækɪt/","n. 夹克；外套","It's cold. Take a jacket.","天冷，带件外套。"],
["shoes","/ʃuːz/","n. 鞋","These shoes are too small.","这双鞋太小了。"],
["bag","/bæɡ/","n. 包；袋子","Do you need a bag?","你需要袋子吗？"],
["cashier","/kæˈʃɪr/","n. 收银员","Please pay at the cashier.","请到收银台付款。"],
["change","/tʃeɪndʒ/","n. 零钱；找零","Here is your change.","这是找您的零钱。"],
["return","/rɪˈtɜːrn/","v. 退货","Can I return this?","这个可以退吗？"],
["gift","/ɡɪft/","n. 礼物","It's a gift for my mother.","这是给我妈妈的礼物。"],
["wrap","/ræp/","v. 包装","Could you wrap it for me?","能帮我包起来吗？"],
];

const HEALTH = [
["health","/helθ/","n. 健康","Health is more important than money.","健康比金钱更重要。"],
["healthy","/ˈhelθi/","adj. 健康的","Try to eat healthy food.","尽量吃健康的食物。"],
["headache","/ˈhedeɪk/","n. 头痛","I have a headache.","我头痛。"],
["fever","/ˈfiːvər/","n. 发烧","I think I have a fever.","我觉得我发烧了。"],
["cough","/kɔːf/","n./v. 咳嗽","I have a bad cough.","我咳嗽得很厉害。"],
["flu","/fluː/","n. 流感","I got the flu last week.","我上周得了流感。"],
["sore throat","/ˌsɔːr ˈθroʊt/","n. 嗓子疼","I have a sore throat.","我嗓子疼。"],
["stomachache","/ˈstʌməkeɪk/","n. 肚子疼","I have a stomachache.","我肚子疼。"],
["pain","/peɪn/","n. 疼痛","I have a pain in my back.","我背疼。"],
["hurt","/hɜːrt/","v. 疼；受伤","My leg hurts.","我腿疼。"],
["dizzy","/ˈdɪzi/","adj. 头晕的","I feel dizzy.","我头晕。"],
["symptom","/ˈsɪmptəm/","n. 症状","What are your symptoms?","你有什么症状？"],
["temperature","/ˈtemprətʃər/","n. 体温；温度","Let me take your temperature.","我给你量一下体温。"],
["allergic","/əˈlɜːrdʒɪk/","adj. 过敏的","I'm allergic to seafood.","我对海鲜过敏。"],
["injury","/ˈɪndʒəri/","n. 伤","It's not a serious injury.","伤得不重。"],
["broken","/ˈbroʊkən/","adj. 断了的；坏了的","I think my arm is broken.","我觉得我的胳膊断了。"],
["blood","/blʌd/","n. 血","I need a blood test.","我需要验血。"],
["tooth","/tuːθ/","n. 牙齿","My tooth hurts.","我牙疼。"],
["dentist","/ˈdentɪst/","n. 牙医","I need to see a dentist.","我需要看牙医。"],
["nurse","/nɜːrs/","n. 护士","The nurse will help you.","护士会帮你。"],
["patient","/ˈpeɪʃnt/","n. 病人","The patient is getting better.","病人在好转。"],
["clinic","/ˈklɪnɪk/","n. 诊所","I went to a clinic.","我去了诊所。"],
["emergency","/ɪˈmɜːrdʒənsi/","n. 紧急情况","This is an emergency!","这是紧急情况！"],
["ambulance","/ˈæmbjələns/","n. 救护车","Call an ambulance, please.","请叫救护车。"],
["medicine","/ˈmedɪsn/","n. 药","Take this medicine twice a day.","这药每天吃两次。"],
["pill","/pɪl/","n. 药片","Take one pill after meals.","饭后吃一片。"],
["pharmacy","/ˈfɑːrməsi/","n. 药店","Is there a pharmacy near here?","这附近有药店吗？"],
["prescription","/prɪˈskrɪpʃn/","n. 处方","You need a prescription for this.","这个药需要处方。"],
["side effect","/ˈsaɪd ɪˌfekt/","n. 副作用","Are there any side effects?","有副作用吗？"],
["check-up","/ˈtʃek ʌp/","n. 体检","I have a check-up every year.","我每年做一次体检。"],
["X-ray","/ˈeks reɪ/","n. X光","You need an X-ray.","你需要拍个X光。"],
["bandage","/ˈbændɪdʒ/","n. 绷带","Put a bandage on it.","用绷带包上。"],
["mask","/mæsk/","n. 口罩","Please wear a mask.","请戴口罩。"],
["vitamin","/ˈvaɪtəmɪn/","n. 维生素","I take vitamins every day.","我每天吃维生素。"],
["recover","/rɪˈkʌvər/","v. 康复","I hope you recover soon.","希望你早日康复。"],
["better","/ˈbetər/","adj. 更好的","I feel much better today.","我今天感觉好多了。"],
["rest","/rest/","n./v. 休息","You should get some rest.","你应该休息一下。"],
["sleep","/sliːp/","v./n. 睡觉","I didn't sleep well last night.","我昨晚没睡好。"],
["exercise","/ˈeksərsaɪz/","n./v. 锻炼","I exercise three times a week.","我每周锻炼三次。"],
["weight","/weɪt/","n. 体重","I want to lose weight.","我想减肥。"],
["diet","/ˈdaɪət/","n. 饮食；节食","I'm on a diet.","我在节食。"],
["stress","/stres/","n. 压力","I'm under a lot of stress.","我压力很大。"],
];

function wordDeck(prefix, title, list) {
  return { title, items: list.map(([w, ipa, cn, ex, exCn]) => ({ id: prefix + ":" + w, front: w, ipa, cn, ex, exCn })) };
}

const DECKS = {
  words: wordDeck("w", "基础单词", WORDS),
  phrases: {
    title: "口语句子",
    items: PHRASES.map(([en, cn]) => ({ id: "p:" + en, front: en, cn })),
  },
  travel: wordDeck("t", "旅游出行", TRAVEL),
  business: wordDeck("b", "商务职场", BUSINESS),
  finance: wordDeck("f", "财务会计", FINANCE),
  dining: wordDeck("d", "餐饮购物", DINING),
  health: wordDeck("h", "健康医疗", HEALTH),
};
