// [单词, 音标, 中文, 例句, 例句翻译]
const WORDS = [
["hello","/həˈloʊ/","int. 你好","Hello, nice to meet you.","你好，很高兴认识你。"],
["thanks","/θæŋks/","int. 谢谢","Thanks for your help.","谢谢你的帮助。"],
["sorry","/ˈsɑːri/","adj. 抱歉的","Sorry, I'm late.","抱歉，我迟到了。"],
["please","/pliːz/","adv. 请","Please sit down.","请坐。"],
["yes","/jes/","adv. 是的","Yes, I can.","是的，我可以。"],
["name","/neɪm/","n. 名字","What's your name?","你叫什么名字？"],
["friend","/frend/","n. 朋友","She is my best friend.","她是我最好的朋友。"],
["family","/ˈfæməli/","n. 家庭；家人","I love my family.","我爱我的家人。"],
["mother","/ˈmʌðər/","n. 母亲","My mother is a teacher.","我妈妈是老师。"],
["father","/ˈfɑːðər/","n. 父亲","My father works in a bank.","我爸爸在银行工作。"],
["child","/tʃaɪld/","n. 孩子","The child is sleeping.","孩子在睡觉。"],
["people","/ˈpiːpl/","n. 人们","Many people like coffee.","很多人喜欢咖啡。"],
["man","/mæn/","n. 男人","That man is very tall.","那个男人很高。"],
["woman","/ˈwʊmən/","n. 女人","The woman is my boss.","那位女士是我的老板。"],
["home","/hoʊm/","n. 家 adv. 回家","I want to go home.","我想回家。"],
["house","/haʊs/","n. 房子","They live in a big house.","他们住在一栋大房子里。"],
["room","/ruːm/","n. 房间","My room is small.","我的房间很小。"],
["door","/dɔːr/","n. 门","Please close the door.","请关门。"],
["window","/ˈwɪndoʊ/","n. 窗户","Can you open the window?","你能打开窗户吗？"],
["table","/ˈteɪbl/","n. 桌子","The keys are on the table.","钥匙在桌子上。"],
["bed","/bed/","n. 床","I go to bed at eleven.","我十一点睡觉。"],
["water","/ˈwɔːtər/","n. 水","Can I have some water?","能给我一些水吗？"],
["food","/fuːd/","n. 食物","The food here is good.","这里的东西很好吃。"],
["rice","/raɪs/","n. 米饭","I eat rice every day.","我每天吃米饭。"],
["bread","/bred/","n. 面包","I have bread for breakfast.","我早餐吃面包。"],
["egg","/eɡ/","n. 鸡蛋","I'd like two eggs, please.","请给我两个鸡蛋。"],
["milk","/mɪlk/","n. 牛奶","Do you want some milk?","你想喝点牛奶吗？"],
["coffee","/ˈkɔːfi/","n. 咖啡","I need a cup of coffee.","我需要一杯咖啡。"],
["tea","/tiː/","n. 茶","Would you like some tea?","你想喝点茶吗？"],
["fruit","/fruːt/","n. 水果","Fruit is good for you.","水果对你有好处。"],
["apple","/ˈæpl/","n. 苹果","An apple a day keeps the doctor away.","一天一苹果，医生远离我。"],
["breakfast","/ˈbrekfəst/","n. 早餐","Did you have breakfast?","你吃早餐了吗？"],
["lunch","/lʌntʃ/","n. 午餐","Let's have lunch together.","我们一起吃午饭吧。"],
["dinner","/ˈdɪnər/","n. 晚餐","Dinner is ready.","晚饭好了。"],
["hungry","/ˈhʌŋɡri/","adj. 饿的","I'm so hungry.","我好饿。"],
["thirsty","/ˈθɜːrsti/","adj. 渴的","Are you thirsty?","你渴吗？"],
["eat","/iːt/","v. 吃","What do you want to eat?","你想吃什么？"],
["drink","/drɪŋk/","v. 喝","I drink water every morning.","我每天早上喝水。"],
["cook","/kʊk/","v. 做饭","Can you cook?","你会做饭吗？"],
["buy","/baɪ/","v. 买","I want to buy a new phone.","我想买一部新手机。"],
["pay","/peɪ/","v. 付钱","Can I pay by card?","我可以刷卡吗？"],
["money","/ˈmʌni/","n. 钱","I don't have much money.","我没有多少钱。"],
["price","/praɪs/","n. 价格","What's the price of this?","这个多少钱？"],
["cheap","/tʃiːp/","adj. 便宜的","This shirt is cheap.","这件衬衫很便宜。"],
["expensive","/ɪkˈspensɪv/","adj. 贵的","It's too expensive.","太贵了。"],
["shop","/ʃɑːp/","n. 商店","The shop opens at nine.","商店九点开门。"],
["time","/taɪm/","n. 时间","What time is it?","现在几点？"],
["day","/deɪ/","n. 天","Have a nice day!","祝你今天愉快！"],
["today","/təˈdeɪ/","adv. 今天","I'm busy today.","我今天很忙。"],
["tomorrow","/təˈmɑːroʊ/","adv. 明天","See you tomorrow.","明天见。"],
["yesterday","/ˈjestərdeɪ/","adv. 昨天","I saw him yesterday.","我昨天见到他了。"],
["morning","/ˈmɔːrnɪŋ/","n. 早上","Good morning!","早上好！"],
["night","/naɪt/","n. 夜晚","Good night.","晚安。"],
["week","/wiːk/","n. 周","I work five days a week.","我一周工作五天。"],
["year","/jɪr/","n. 年","Happy New Year!","新年快乐！"],
["now","/naʊ/","adv. 现在","I'm coming now.","我现在就来。"],
["later","/ˈleɪtər/","adv. 稍后","Talk to you later.","回头再聊。"],
["early","/ˈɜːrli/","adj./adv. 早","I get up early.","我起得很早。"],
["late","/leɪt/","adj. 晚的；迟的","Don't be late.","别迟到。"],
["work","/wɜːrk/","v./n. 工作","I go to work by bus.","我坐公交上班。"],
["job","/dʒɑːb/","n. 工作；职业","I like my job.","我喜欢我的工作。"],
["office","/ˈɔːfɪs/","n. 办公室","He is in the office.","他在办公室。"],
["meeting","/ˈmiːtɪŋ/","n. 会议","I have a meeting at ten.","我十点有个会。"],
["busy","/ˈbɪzi/","adj. 忙的","Are you busy now?","你现在忙吗？"],
["free","/friː/","adj. 空闲的；免费的","Are you free tonight?","你今晚有空吗？"],
["school","/skuːl/","n. 学校","My son goes to school.","我儿子在上学。"],
["teacher","/ˈtiːtʃər/","n. 老师","Our teacher is very kind.","我们的老师很和蔼。"],
["student","/ˈstuːdnt/","n. 学生","I am a student.","我是学生。"],
["learn","/lɜːrn/","v. 学习","I want to learn English.","我想学英语。"],
["study","/ˈstʌdi/","v. 学习；研究","I study every evening.","我每天晚上学习。"],
["book","/bʊk/","n. 书","This book is interesting.","这本书很有趣。"],
["read","/riːd/","v. 读","I read before bed.","我睡前看书。"],
["write","/raɪt/","v. 写","Please write your name here.","请在这里写你的名字。"],
["speak","/spiːk/","v. 说（语言）","Do you speak English?","你会说英语吗？"],
["say","/seɪ/","v. 说","What did you say?","你说什么？"],
["tell","/tel/","v. 告诉","Can you tell me the way?","你能告诉我怎么走吗？"],
["talk","/tɔːk/","v. 谈话","Can we talk?","我们能谈谈吗？"],
["ask","/æsk/","v. 问","Can I ask a question?","我可以问个问题吗？"],
["answer","/ˈænsər/","n./v. 回答","I don't know the answer.","我不知道答案。"],
["understand","/ˌʌndərˈstænd/","v. 理解","I don't understand.","我不明白。"],
["know","/noʊ/","v. 知道","I know what you mean.","我知道你的意思。"],
["think","/θɪŋk/","v. 想；认为","I think so.","我也这么认为。"],
["want","/wɑːnt/","v. 想要","I want a cup of tea.","我想要一杯茶。"],
["need","/niːd/","v. 需要","I need your help.","我需要你的帮助。"],
["like","/laɪk/","v. 喜欢","I like music.","我喜欢音乐。"],
["love","/lʌv/","v. 爱","I love this city.","我爱这座城市。"],
["help","/help/","v./n. 帮助","Can you help me?","你能帮我吗？"],
["go","/ɡoʊ/","v. 去","Let's go!","我们走吧！"],
["come","/kʌm/","v. 来","Come here, please.","请过来。"],
["get","/ɡet/","v. 得到；到达","When did you get here?","你什么时候到的？"],
["make","/meɪk/","v. 做；制作","I'll make some tea.","我去泡点茶。"],
["take","/teɪk/","v. 拿；乘坐","I take the subway to work.","我坐地铁上班。"],
["give","/ɡɪv/","v. 给","Please give me a minute.","请给我一分钟。"],
["see","/siː/","v. 看见","Nice to see you again.","很高兴再次见到你。"],
["look","/lʊk/","v. 看","Look at this photo.","看看这张照片。"],
["watch","/wɑːtʃ/","v. 观看","I watch TV at night.","我晚上看电视。"],
["listen","/ˈlɪsn/","v. 听","Listen to me, please.","请听我说。"],
["hear","/hɪr/","v. 听见","Can you hear me?","你能听到我说话吗？"],
["feel","/fiːl/","v. 感觉","I feel tired.","我觉得累。"],
["try","/traɪ/","v. 尝试","Let me try again.","让我再试一次。"],
["wait","/weɪt/","v. 等待","Please wait a moment.","请稍等。"],
["stop","/stɑːp/","v. 停止","Please stop here.","请在这里停。"],
["open","/ˈoʊpən/","v. 打开","What time do you open?","你们几点开门？"],
["close","/kloʊz/","v. 关闭","Please close the window.","请关上窗户。"],
["call","/kɔːl/","v. 打电话","I'll call you later.","我晚点给你打电话。"],
["phone","/foʊn/","n. 手机；电话","My phone is dead.","我手机没电了。"],
["car","/kɑːr/","n. 汽车","I drive my car to work.","我开车上班。"],
["bus","/bʌs/","n. 公交车","Where is the bus stop?","公交车站在哪里？"],
["train","/treɪn/","n. 火车","The train is late.","火车晚点了。"],
["airport","/ˈerpɔːrt/","n. 机场","How do I get to the airport?","我怎么去机场？"],
["hotel","/hoʊˈtel/","n. 酒店","I booked a hotel room.","我订了一间酒店房间。"],
["ticket","/ˈtɪkɪt/","n. 票","One ticket, please.","请给我一张票。"],
["street","/striːt/","n. 街道","This street is very busy.","这条街很热闹。"],
["left","/left/","n./adv. 左边","Turn left here.","在这里左转。"],
["right","/raɪt/","adj. 右边的；正确的","You are right.","你说得对。"],
["near","/nɪr/","prep./adj. 在附近","Is there a bank near here?","这附近有银行吗？"],
["far","/fɑːr/","adj. 远的","Is it far from here?","离这里远吗？"],
["here","/hɪr/","adv. 这里","I'm here.","我在这儿。"],
["there","/ðer/","adv. 那里","Put it over there.","把它放在那边。"],
["weather","/ˈweðər/","n. 天气","The weather is nice today.","今天天气很好。"],
["hot","/hɑːt/","adj. 热的","It's very hot today.","今天很热。"],
["cold","/koʊld/","adj. 冷的","I'm cold.","我冷。"],
["rain","/reɪn/","n. 雨 v. 下雨","It might rain tomorrow.","明天可能会下雨。"],
["good","/ɡʊd/","adj. 好的","That's a good idea.","那是个好主意。"],
["bad","/bæd/","adj. 坏的；严重的","I have a bad cold.","我得了重感冒。"],
["big","/bɪɡ/","adj. 大的","This box is too big.","这个箱子太大了。"],
["small","/smɔːl/","adj. 小的","Do you have a small size?","有小号吗？"],
["new","/nuː/","adj. 新的","I have a new job.","我有了一份新工作。"],
["old","/oʊld/","adj. 旧的；老的","How old are you?","你多大了？"],
["happy","/ˈhæpi/","adj. 开心的","I'm happy to help.","我很乐意帮忙。"],
["sad","/sæd/","adj. 难过的","Why are you sad?","你为什么难过？"],
["tired","/ˈtaɪərd/","adj. 累的","I'm tired after work.","下班后我很累。"],
["easy","/ˈiːzi/","adj. 容易的","This is easy.","这很简单。"],
["difficult","/ˈdɪfɪkəlt/","adj. 困难的","English is not difficult.","英语并不难。"],
["beautiful","/ˈbjuːtɪfl/","adj. 美丽的","What a beautiful day!","多美好的一天！"],
["sick","/sɪk/","adj. 生病的","I feel sick.","我感觉不舒服。"],
["doctor","/ˈdɑːktər/","n. 医生","You should see a doctor.","你应该去看医生。"],
["hospital","/ˈhɑːspɪtl/","n. 医院","Where is the hospital?","医院在哪里？"],
["again","/əˈɡen/","adv. 再一次","Could you say that again?","你能再说一遍吗？"],
["slowly","/ˈsloʊli/","adv. 慢慢地","Please speak slowly.","请说慢一点。"],
["maybe","/ˈmeɪbi/","adv. 也许","Maybe next time.","也许下次吧。"],
["really","/ˈriːəli/","adv. 真的","Really? I didn't know that.","真的吗？我不知道。"],
["very","/ˈveri/","adv. 非常","Thank you very much.","非常感谢。"],
["always","/ˈɔːlweɪz/","adv. 总是","I always get up at seven.","我总是七点起床。"],
["never","/ˈnevər/","adv. 从不","I never drink coffee at night.","我晚上从不喝咖啡。"],
["together","/təˈɡeðər/","adv. 一起","Let's go together.","我们一起去吧。"],
["weekend","/ˈwiːkend/","n. 周末","What did you do on the weekend?","你周末做了什么？"],
["movie","/ˈmuːvi/","n. 电影","Let's watch a movie.","我们看部电影吧。"],
["music","/ˈmjuːzɪk/","n. 音乐","What music do you like?","你喜欢什么音乐？"],
["photo","/ˈfoʊtoʊ/","n. 照片","Can you take a photo of us?","你能帮我们拍张照吗？"],
];

// [英文句子, 中文]
const PHRASES = [
["How are you?","你好吗？"],
["I'm fine, thank you. And you?","我很好，谢谢。你呢？"],
["Nice to meet you.","很高兴认识你。"],
["Where are you from?","你来自哪里？"],
["I'm from China.","我来自中国。"],
["What do you do?","你是做什么工作的？"],
["I'm learning English.","我在学英语。"],
["Excuse me, where is the restroom?","打扰一下，洗手间在哪里？"],
["Could you help me, please?","你能帮我一下吗？"],
["I'm sorry, I don't understand.","抱歉，我不明白。"],
["Could you speak more slowly?","你能说慢一点吗？"],
["Pardon?","请再说一遍？"],
["What does this mean?","这是什么意思？"],
["How do you say this in English?","这个用英语怎么说？"],
["How much is it?","这个多少钱？"],
["I'm just looking, thanks.","我只是看看，谢谢。"],
["Do you have this in a bigger size?","这个有大一号的吗？"],
["Can I try it on?","我可以试穿吗？"],
["I'll take it.","我买了。"],
["Can I have the bill, please?","请给我账单。"],
["I'd like a coffee, please.","我想要一杯咖啡。"],
["A table for two, please.","请给我们一张两人桌。"],
["Can I see the menu?","我能看一下菜单吗？"],
["This is delicious.","这个很好吃。"],
["I'm full.","我吃饱了。"],
["I'm allergic to peanuts.","我对花生过敏。"],
["How do I get to the station?","我怎么去车站？"],
["It's about ten minutes on foot.","走路大约十分钟。"],
["I'm looking for this address.","我在找这个地址。"],
["I have a reservation.","我有预订。"],
["What's the Wi-Fi password?","Wi-Fi 密码是多少？"],
["My phone is out of battery.","我的手机没电了。"],
["What time does it start?","几点开始？"],
["Let's meet at six.","我们六点见吧。"],
["I'm on my way.","我在路上了。"],
["Sorry to keep you waiting.","抱歉让你久等了。"],
["Sounds good.","听起来不错。"],
["No problem.","没问题。"],
["Don't worry.","别担心。"],
["Take your time.","慢慢来，不着急。"],
["You're welcome.","不客气。"],
["It's my pleasure.","我很乐意。"],
["What do you think?","你觉得呢？"],
["I agree with you.","我同意你的看法。"],
["I'm not sure.","我不太确定。"],
["That makes sense.","有道理。"],
["Let me think about it.","让我想一想。"],
["What's the weather like today?","今天天气怎么样？"],
["I don't feel well.","我不太舒服。"],
["Call an ambulance!","快叫救护车！"],
["Have a good weekend!","周末愉快！"],
["See you soon.","回头见。"],
["Take care.","保重。"],
["Practice makes perfect.","熟能生巧。"],
];

const DECKS = {
  words: {
    title: "基础单词",
    items: WORDS.map(([w, ipa, cn, ex, exCn]) => ({ id: "w:" + w, front: w, ipa, cn, ex, exCn })),
  },
  phrases: {
    title: "口语句子",
    items: PHRASES.map(([en, cn]) => ({ id: "p:" + en, front: en, cn })),
  },
};
