// 追加在原有板块末尾（保持已有学习顺序不变）
TRAVEL.push(
["airline","/ˈerlaɪn/","n. 航空公司","Which airline are you flying with?","你坐哪家航空公司的飞机？"],
["terminal","/ˈtɜːrmɪnl/","n. 航站楼","Our flight leaves from Terminal 2.","我们的航班从2号航站楼出发。"],
["baggage claim","/ˈbæɡɪdʒ kleɪm/","n. 行李提取处","Let's go to baggage claim.","我们去行李提取处吧。"],
["economy class","/ɪˈkɑːnəmi klæs/","n. 经济舱","I usually fly economy class.","我通常坐经济舱。"],
["business class","/ˈbɪznəs klæs/","n. 商务舱","The company booked business class for me.","公司给我订了商务舱。"],
["flight attendant","/ˈflaɪt əˌtendənt/","n. 空乘","The flight attendant was very kind.","空乘人员非常友善。"],
["seat belt","/ˈsiːt belt/","n. 安全带","Please fasten your seat belt.","请系好安全带。"],
["layover","/ˈleɪoʊvər/","n. 中途停留","We have a three-hour layover in Singapore.","我们在新加坡停留三小时。"],
["immigration","/ˌɪmɪˈɡreɪʃn/","n. 入境检查","The line at immigration is very long.","入境检查的队伍很长。"],
["purpose","/ˈpɜːrpəs/","n. 目的","What's the purpose of your visit?","您此行的目的是什么？"],
["stay","/steɪ/","v./n. 停留；住","How long will you stay?","你会待多久？"],
["duty-free","/ˌduːti ˈfriː/","adj. 免税的","Let's go to the duty-free shop.","我们去免税店吧。"],
["booking","/ˈbʊkɪŋ/","n. 预订","I have a booking under the name Li.","我用李的名字预订了。"],
["vacancy","/ˈveɪkənsi/","n. 空房","Do you have any vacancies tonight?","你们今晚还有空房吗？"],
["air conditioner","/ˈer kənˌdɪʃənər/","n. 空调","The air conditioner doesn't work.","空调坏了。"],
["noisy","/ˈnɔɪzi/","adj. 吵的","My room is too noisy.","我的房间太吵了。"],
["upgrade","/ˈʌpɡreɪd/","n./v. 升级","Can I upgrade my room?","我可以升级房间吗？"],
["floor","/flɔːr/","n. 楼层；地板","My room is on the fifth floor.","我的房间在五楼。"],
["luggage storage","/ˈlʌɡɪdʒ ˌstɔːrɪdʒ/","n. 行李寄存","Do you have luggage storage?","你们有行李寄存吗？"],
["address","/ˈædres/","n. 地址","Can you write down the address?","你能把地址写下来吗？"],
["taxi stand","/ˈtæksi stænd/","n. 出租车站","Where is the taxi stand?","出租车站在哪里？"],
["fare","/fer/","n. 车费","How much is the fare?","车费多少钱？"],
["meter","/ˈmiːtər/","n. 计价器","Please use the meter.","请打表。"],
["transit","/ˈtrænzɪt/","n. 公共交通；中转","Public transit is very convenient here.","这里的公共交通很方便。"],
["timetable","/ˈtaɪmteɪbl/","n. 时刻表","Can I see the train timetable?","我能看一下火车时刻表吗？"],
["route","/ruːt/","n. 路线","Which route is the fastest?","哪条路线最快？"],
["crosswalk","/ˈkrɔːswɔːk/","n. 人行横道","Cross at the crosswalk.","走人行横道过马路。"],
["bridge","/brɪdʒ/","n. 桥","Walk across the bridge.","走过那座桥。"],
["landmark","/ˈlændmɑːrk/","n. 地标","The tower is a famous landmark.","那座塔是著名地标。"],
["attraction","/əˈtrækʃn/","n. 景点","What are the main attractions here?","这里主要的景点有哪些？"],
["scenery","/ˈsiːnəri/","n. 风景","The scenery is beautiful.","风景很美。"],
["castle","/ˈkæsl/","n. 城堡","We visited an old castle.","我们参观了一座古堡。"],
["gallery","/ˈɡæləri/","n. 美术馆","The art gallery is free.","美术馆免费。"],
["zoo","/zuː/","n. 动物园","The kids love the zoo.","孩子们喜欢动物园。"],
["lake","/leɪk/","n. 湖","Let's take a walk by the lake.","我们去湖边散步吧。"],
["river","/ˈrɪvər/","n. 河","We took a boat on the river.","我们在河上坐了船。"],
["sea","/siː/","n. 海","I want to swim in the sea.","我想去海里游泳。"],
["festival","/ˈfestɪvl/","n. 节日；节庆","There's a music festival this weekend.","这周末有个音乐节。"],
["culture","/ˈkʌltʃər/","n. 文化","I'm interested in the local culture.","我对当地文化很感兴趣。"],
["crowded","/ˈkraʊdɪd/","adj. 拥挤的","The train is very crowded.","火车很挤。"],
["opening hours","/ˈoʊpənɪŋ ˌaʊərz/","n. 营业时间","What are the opening hours?","营业时间是几点到几点？"],
["admission","/ədˈmɪʃn/","n. 门票；入场","How much is admission?","门票多少钱？"],
["brochure","/broʊˈʃʊr/","n. 宣传册","Can I have a brochure?","能给我一本宣传册吗？"],
["guidebook","/ˈɡaɪdbʊk/","n. 旅游指南","The guidebook says it's open today.","旅游指南上说今天开门。"],
["travel agency","/ˈtrævl ˌeɪdʒənsi/","n. 旅行社","We booked the trip through a travel agency.","我们通过旅行社订的行程。"],
["forecast","/ˈfɔːrkæst/","n. 预报","What's the weather forecast?","天气预报怎么说？"],
["wallet","/ˈwɑːlɪt/","n. 钱包","I lost my wallet.","我的钱包丢了。"],
["steal","/stiːl/","v. 偷","Someone stole my bag.","有人偷了我的包。"],
["safe","/seɪf/","adj. 安全的","Is this area safe at night?","这个地区晚上安全吗？"],
["dangerous","/ˈdeɪndʒərəs/","adj. 危险的","It's dangerous to swim here.","在这里游泳很危险。"],
["SIM card","/ˈsɪm kɑːrd/","n. 手机卡","Where can I buy a SIM card?","我在哪里可以买手机卡？"],
["power bank","/ˈpaʊər bæŋk/","n. 充电宝","Can I bring a power bank on the plane?","我可以带充电宝上飞机吗？"],
["selfie","/ˈselfi/","n. 自拍","Let's take a selfie.","我们来自拍吧。"],
);

BUSINESS.push(
["meeting room","/ˈmiːtɪŋ ruːm/","n. 会议室","The meeting room is booked.","会议室已经被订了。"],
["video call","/ˈvɪdioʊ kɔːl/","n. 视频通话","Let's have a video call tomorrow.","我们明天视频通话吧。"],
["mute","/mjuːt/","v. 静音","You're on mute.","你开着静音呢。"],
["screen","/skriːn/","n. 屏幕","Can you share your screen?","你能共享一下屏幕吗？"],
["time zone","/ˈtaɪm zoʊn/","n. 时区","We are in different time zones.","我们在不同的时区。"],
["calendar","/ˈkælɪndər/","n. 日历","I'll send you a calendar invite.","我给你发个日历邀请。"],
["invite","/ɪnˈvaɪt/","v. 邀请","I'd like to invite you to our event.","我想邀请你参加我们的活动。"],
["minutes","/ˈmɪnɪts/","n. 会议纪要","Who will take the minutes?","谁来做会议纪要？"],
["summary","/ˈsʌməri/","n. 总结","Please send a summary after the meeting.","会后请发一份总结。"],
["point","/pɔɪnt/","n. 要点；观点","That's a good point.","这一点说得好。"],
["clarify","/ˈklærəfaɪ/","v. 澄清；说明","Could you clarify that?","你能解释清楚一点吗？"],
["explain","/ɪkˈspleɪn/","v. 解释","Let me explain.","我来解释一下。"],
["priority","/praɪˈɔːrəti/","n. 优先事项","What's our top priority?","我们的首要任务是什么？"],
["task","/tæsk/","n. 任务","I have many tasks today.","我今天有很多任务。"],
["assign","/əˈsaɪn/","v. 分配","I'll assign this task to Tom.","我把这个任务分给汤姆。"],
["in charge","/ɪn ˈtʃɑːrdʒ/","负责","Who is in charge of this project?","谁负责这个项目？"],
["support","/səˈpɔːrt/","n./v. 支持","Thanks for your support.","谢谢你的支持。"],
["handle","/ˈhændl/","v. 处理","I'll handle it.","我来处理。"],
["issue","/ˈɪʃuː/","n. 问题","We fixed the issue.","我们解决了这个问题。"],
["fix","/fɪks/","v. 修复","Can you fix this bug?","你能修复这个漏洞吗？"],
["double-check","/ˌdʌbl ˈtʃek/","v. 再次确认","Please double-check the numbers.","请再核对一下数字。"],
["detail","/ˈdiːteɪl/","n. 细节","Let's discuss the details.","我们讨论一下细节。"],
["requirement","/rɪˈkwaɪərmənt/","n. 要求","What are the client's requirements?","客户的要求是什么？"],
["expectation","/ˌekspekˈteɪʃn/","n. 期望","The results met our expectations.","结果达到了我们的预期。"],
["negotiation","/nɪˌɡoʊʃiˈeɪʃn/","n. 谈判","The negotiation went well.","谈判很顺利。"],
["terms","/tɜːrmz/","n. 条款","Let's go over the terms.","我们过一下条款。"],
["renew","/rɪˈnuː/","v. 续签","We want to renew the contract.","我们想续签合同。"],
["long-term","/ˌlɔːŋ ˈtɜːrm/","adj. 长期的","We want a long-term partnership.","我们希望建立长期合作关系。"],
["partnership","/ˈpɑːrtnərʃɪp/","n. 合作关系","We value our partnership.","我们重视彼此的合作关系。"],
["trust","/trʌst/","n./v. 信任","Thank you for trusting us.","感谢您信任我们。"],
["reliable","/rɪˈlaɪəbl/","adj. 可靠的","They are a reliable partner.","他们是可靠的合作伙伴。"],
["professional","/prəˈfeʃənl/","adj. 专业的","Your team is very professional.","你们团队很专业。"],
["efficient","/ɪˈfɪʃnt/","adj. 高效的","This new tool is very efficient.","这个新工具很高效。"],
["flexible","/ˈfleksəbl/","adj. 灵活的","Our working hours are flexible.","我们的工作时间很灵活。"],
["remote","/rɪˈmoʊt/","adj. 远程的","We have a remote team.","我们有一个远程团队。"],
["overtime","/ˈoʊvərtaɪm/","n. 加班","I worked overtime last night.","我昨晚加班了。"],
["day off","/ˌdeɪ ˈɔːf/","n. 休息日","I'm taking a day off tomorrow.","我明天请一天假。"],
["leave","/liːv/","n. 休假","She is on maternity leave.","她在休产假。"],
["employee","/ɪmˈplɔɪiː/","n. 员工","We have two hundred employees.","我们有两百名员工。"],
["employer","/ɪmˈplɔɪər/","n. 雇主","My employer pays for my training.","我的雇主给我付培训费。"],
["CEO","/ˌsiː iː ˈoʊ/","n. 首席执行官","Our CEO will give a speech.","我们的CEO将发表讲话。"],
["director","/dəˈrektər/","n. 总监","She is our creative director.","她是我们的创意总监。"],
["assistant","/əˈsɪstənt/","n. 助理","Please ask my assistant.","请问我的助理。"],
["intern","/ˈɪntɜːrn/","n. 实习生","We have three new interns.","我们有三个新实习生。"],
["training","/ˈtreɪnɪŋ/","n. 培训","The training starts at nine.","培训九点开始。"],
["career","/kəˈrɪr/","n. 职业生涯","I want to grow my career.","我想发展我的职业。"],
["resign","/rɪˈzaɪn/","v. 辞职","He resigned last month.","他上个月辞职了。"],
["position","/pəˈzɪʃn/","n. 职位","We have an open position.","我们有一个空缺职位。"],
["apply","/əˈplaɪ/","v. 申请","I want to apply for this job.","我想申请这份工作。"],
["announce","/əˈnaʊns/","v. 宣布","We will announce the news tomorrow.","我们明天宣布这个消息。"],
["achieve","/əˈtʃiːv/","v. 实现","We achieved our goal.","我们实现了目标。"],
["improve","/ɪmˈpruːv/","v. 改进","How can we improve?","我们怎么改进？"],
["challenge","/ˈtʃælɪndʒ/","n. 挑战","This is a big challenge.","这是个很大的挑战。"],
["opportunity","/ˌɑːpərˈtuːnəti/","n. 机会","It's a great opportunity.","这是个很好的机会。"],
["appreciate","/əˈpriːʃieɪt/","v. 感激","I really appreciate your help.","非常感谢你的帮助。"],
["apologize","/əˈpɑːlədʒaɪz/","v. 道歉","I apologize for the delay.","抱歉耽误了。"],
["inconvenience","/ˌɪnkənˈviːniəns/","n. 不便","Sorry for the inconvenience.","抱歉给您带来不便。"],
["as soon as possible","/əz ˌsuːn əz ˈpɑːsəbl/","尽快","Please reply as soon as possible.","请尽快回复。"],
["regards","/rɪˈɡɑːrdz/","n. 问候（邮件结尾）","Best regards, Li Na.","此致，李娜。"],
);

FINANCE.push(
["ATM","/ˌeɪ tiː ˈem/","n. 自动取款机","Is there an ATM nearby?","附近有取款机吗？"],
["PIN","/pɪn/","n. 密码","Please enter your PIN.","请输入密码。"],
["debit card","/ˈdebɪt kɑːrd/","n. 借记卡","I'll pay with my debit card.","我用借记卡付。"],
["savings account","/ˈseɪvɪŋz əˌkaʊnt/","n. 储蓄账户","I opened a savings account.","我开了一个储蓄账户。"],
["online banking","/ˌɑːnlaɪn ˈbæŋkɪŋ/","n. 网上银行","I use online banking every day.","我每天都用网上银行。"],
["mobile payment","/ˌmoʊbl ˈpeɪmənt/","n. 移动支付","Mobile payment is very popular in China.","移动支付在中国很普及。"],
["QR code","/ˌkjuː ˈɑːr koʊd/","n. 二维码","Please scan the QR code.","请扫二维码。"],
["scan","/skæn/","v. 扫描","Can I scan to pay?","我可以扫码支付吗？"],
["coin","/kɔɪn/","n. 硬币","I don't have any coins.","我没有硬币。"],
["dollar","/ˈdɑːlər/","n. 美元","It costs ten dollars.","这个十美元。"],
["euro","/ˈjʊroʊ/","n. 欧元","Can I pay in euros?","我可以用欧元付吗？"],
["handling fee","/ˈhændlɪŋ fiː/","n. 手续费","Is there a handling fee?","有手续费吗？"],
["penalty","/ˈpenəlti/","n. 罚款；违约金","There's a penalty for late payment.","逾期付款有罚金。"],
["prepayment","/ˌpriːˈpeɪmənt/","n. 预付款","We need a thirty percent prepayment.","我们需要百分之三十的预付款。"],
["down payment","/ˈdaʊn ˌpeɪmənt/","n. 首付","We paid the down payment.","我们付了首付。"],
["mortgage","/ˈmɔːrɡɪdʒ/","n. 房贷","I'm paying off my mortgage.","我在还房贷。"],
["pay off","/ˌpeɪ ˈɔːf/","v. 还清","I paid off my credit card.","我还清了信用卡。"],
["owe","/oʊ/","v. 欠","How much do I owe you?","我欠你多少钱？"],
["lend","/lend/","v. 借出","Can you lend me some money?","你能借我点钱吗？"],
["borrow","/ˈbɑːroʊ/","v. 借入","I need to borrow some money.","我需要借点钱。"],
["financial","/faɪˈnænʃl/","adj. 财务的","We have some financial problems.","我们有些财务问题。"],
["month-end","/ˌmʌnθ ˈend/","n. 月末","We close the books at month-end.","我们在月底结账。"],
["ledger","/ˈledʒər/","n. 账簿；分类账","Please update the ledger.","请更新账簿。"],
["entry","/ˈentri/","n. 分录；记录","This entry is wrong.","这笔分录错了。"],
["voucher","/ˈvaʊtʃər/","n. 凭证","Please attach the voucher.","请附上凭证。"],
["expense report","/ɪkˈspens rɪˌpɔːrt/","n. 费用报告","Submit your expense report by Friday.","周五前提交你的费用报告。"],
["VAT","/ˌviː eɪ ˈtiː/","n. 增值税","Is VAT included in the price?","价格含增值税吗？"],
["tax return","/ˈtæks rɪˌtɜːrn/","n. 纳税申报","I need to file my tax return.","我需要申报纳税。"],
["payroll","/ˈpeɪroʊl/","n. 薪资发放","Payroll is on the fifth of every month.","每月五号发工资。"],
["valuation","/ˌvæljuˈeɪʃn/","n. 估值","The company's valuation is very high.","公司估值很高。"],
["IPO","/ˌaɪ piː ˈoʊ/","n. 首次公开募股","The company plans an IPO next year.","公司计划明年上市。"],
["shareholder","/ˈʃerhoʊldər/","n. 股东","The shareholders will meet in June.","股东们将在六月开会。"],
["capital","/ˈkæpɪtl/","n. 资本","We need more capital to grow.","我们需要更多资本来发展。"],
["bankrupt","/ˈbæŋkrʌpt/","adj. 破产的","The company went bankrupt.","那家公司破产了。"],
["recession","/rɪˈseʃn/","n. 经济衰退","Many people lost jobs in the recession.","很多人在经济衰退中失业了。"],
["margin","/ˈmɑːrdʒɪn/","n. 利润率","Our profit margin is low.","我们的利润率很低。"],
["break even","/ˌbreɪk ˈiːvn/","v. 收支平衡","We will break even this year.","我们今年将实现收支平衡。"],
["fixed cost","/ˌfɪkst ˈkɔːst/","n. 固定成本","Rent is a fixed cost.","房租是固定成本。"],
["payment terms","/ˈpeɪmənt tɜːrmz/","n. 付款条件","Our payment terms are thirty days.","我们的付款条件是30天。"],
["outstanding","/aʊtˈstændɪŋ/","adj. 未付的","There's still an outstanding balance.","还有一笔未付余额。"],
["collect","/kəˈlekt/","v. 收（款）","We need to collect the payment this week.","我们这周需要收回货款。"],
["remind","/rɪˈmaɪnd/","v. 提醒","Please remind the client to pay.","请提醒客户付款。"],
);

DINING.push(
["starter","/ˈstɑːrtər/","n. 开胃菜","What would you like as a starter?","您想要什么开胃菜？"],
["main course","/ˌmeɪn ˈkɔːrs/","n. 主菜","For the main course, I'll have the steak.","主菜我要牛排。"],
["steak","/steɪk/","n. 牛排","How would you like your steak?","您的牛排要几分熟？"],
["medium","/ˈmiːdiəm/","adj. 中等的；五分熟","Medium, please.","五分熟，谢谢。"],
["well-done","/ˌwel ˈdʌn/","adj. 全熟的","I'd like it well-done.","我要全熟的。"],
["salad","/ˈsæləd/","n. 沙拉","I'll have a green salad.","我要一份蔬菜沙拉。"],
["sandwich","/ˈsænwɪtʃ/","n. 三明治","A chicken sandwich, please.","请来一个鸡肉三明治。"],
["pizza","/ˈpiːtsə/","n. 比萨","Let's order a pizza.","我们点个比萨吧。"],
["seafood","/ˈsiːfuːd/","n. 海鲜","This restaurant is famous for seafood.","这家餐厅以海鲜出名。"],
["shrimp","/ʃrɪmp/","n. 虾","Is there shrimp in this dish?","这道菜里有虾吗？"],
["lamb","/læm/","n. 羊肉","The lamb is very tender.","羊肉很嫩。"],
["potato","/pəˈteɪtoʊ/","n. 土豆","I'd like mashed potatoes.","我要土豆泥。"],
["tomato","/təˈmeɪtoʊ/","n. 西红柿","No tomatoes, please.","请不要放西红柿。"],
["onion","/ˈʌnjən/","n. 洋葱","Could you leave out the onions?","能不放洋葱吗？"],
["garlic","/ˈɡɑːrlɪk/","n. 大蒜","I don't like garlic.","我不喜欢大蒜。"],
["sugar","/ˈʃʊɡər/","n. 糖","Coffee with no sugar, please.","咖啡不加糖，谢谢。"],
["salt","/sɔːlt/","n. 盐","Could you pass the salt?","能把盐递给我吗？"],
["sauce","/sɔːs/","n. 酱汁","Can I have more sauce?","能多给我点酱汁吗？"],
["wine","/waɪn/","n. 葡萄酒","A glass of red wine, please.","请来一杯红葡萄酒。"],
["cup","/kʌp/","n. 杯子","Can I have a paper cup?","能给我一个纸杯吗？"],
["glass","/ɡlæs/","n. 玻璃杯；一杯","Two glasses of water, please.","请来两杯水。"],
["straw","/strɔː/","n. 吸管","Can I have a straw?","能给我一根吸管吗？"],
["refill","/ˈriːfɪl/","n. 续杯","Can I get a refill?","能续杯吗？"],
["portion","/ˈpɔːrʃn/","n. 一份；分量","The portions here are big.","这里的分量很大。"],
["taste","/teɪst/","v./n. 尝；味道","It tastes great.","味道很棒。"],
["flavor","/ˈfleɪvər/","n. 口味","What flavors do you have?","你们有什么口味？"],
["bitter","/ˈbɪtər/","adj. 苦的","This coffee is too bitter.","这咖啡太苦了。"],
["restaurant","/ˈrestərɑːnt/","n. 餐厅","Do you know a good restaurant near here?","你知道这附近有好餐厅吗？"],
["café","/kæˈfeɪ/","n. 咖啡馆","Let's meet at the café.","我们在咖啡馆见吧。"],
["buffet","/bəˈfeɪ/","n. 自助餐","The hotel has a breakfast buffet.","酒店有自助早餐。"],
["leftovers","/ˈleftoʊvərz/","n. 剩菜","Can I take the leftovers home?","剩菜我可以打包回家吗？"],
["box","/bɑːks/","n. 盒子；打包盒","Can I have a box for this?","能给我个打包盒吗？"],
["split the bill","/ˌsplɪt ðə ˈbɪl/","AA制","Let's split the bill.","我们AA吧。"],
["treat","/triːt/","v./n. 请客","It's my treat today.","今天我请客。"],
["cheers","/tʃɪrz/","int. 干杯","Cheers!","干杯！"],
["queue","/kjuː/","n./v. 排队","There's a long queue outside.","外面排了很长的队。"],
["coupon","/ˈkuːpɑːn/","n. 优惠券","Can I use this coupon?","我能用这张优惠券吗？"],
["member","/ˈmembər/","n. 会员","Are you a member?","您是会员吗？"],
["brand-new","/ˌbrænd ˈnuː/","adj. 全新的","Is it brand-new?","这是全新的吗？"],
["material","/məˈtɪriəl/","n. 材料；面料","What material is this?","这是什么材料的？"],
["cotton","/ˈkɑːtn/","n. 棉","This shirt is made of cotton.","这件衬衫是棉的。"],
["fit","/fɪt/","v. 合身","It doesn't fit me.","这个我穿不合身。"],
["loose","/luːs/","adj. 宽松的","These pants are a bit loose.","这条裤子有点松。"],
["tight","/taɪt/","adj. 紧的","The shoes are too tight.","这双鞋太紧了。"],
["hat","/hæt/","n. 帽子","I like your hat.","我喜欢你的帽子。"],
["socks","/sɑːks/","n. 袜子","I need a pair of socks.","我需要一双袜子。"],
["cosmetics","/kɑːzˈmetɪks/","n. 化妆品","Where is the cosmetics section?","化妆品区在哪里？"],
["perfume","/pərˈfjuːm/","n. 香水","This perfume smells nice.","这款香水很好闻。"],
);

HEALTH.push(
["runny nose","/ˌrʌni ˈnoʊz/","n. 流鼻涕","I have a runny nose.","我流鼻涕。"],
["sneeze","/sniːz/","v. 打喷嚏","I keep sneezing.","我一直打喷嚏。"],
["throw up","/ˌθroʊ ˈʌp/","v. 呕吐","I feel like I'm going to throw up.","我想吐。"],
["diarrhea","/ˌdaɪəˈriːə/","n. 腹泻","I have diarrhea.","我拉肚子。"],
["food poisoning","/ˈfuːd ˌpɔɪzənɪŋ/","n. 食物中毒","I think I have food poisoning.","我觉得我食物中毒了。"],
["cut","/kʌt/","v./n. 割伤；伤口","I cut my finger.","我割破了手指。"],
["bleed","/bliːd/","v. 流血","My nose is bleeding.","我流鼻血了。"],
["burn","/bɜːrn/","v./n. 烧伤；烫伤","I burned my hand.","我烫伤了手。"],
["swollen","/ˈswoʊlən/","adj. 肿的","My ankle is swollen.","我的脚踝肿了。"],
["itchy","/ˈɪtʃi/","adj. 痒的","My skin is itchy.","我的皮肤很痒。"],
["rash","/ræʃ/","n. 皮疹","I have a rash on my arm.","我胳膊上起了疹子。"],
["exhausted","/ɪɡˈzɔːstɪd/","adj. 筋疲力尽的","I'm exhausted after the trip.","旅行后我筋疲力尽。"],
["head","/hed/","n. 头","My head hurts.","我头疼。"],
["eye","/aɪ/","n. 眼睛","My eyes are tired.","我眼睛很累。"],
["ear","/ɪr/","n. 耳朵","My ear hurts.","我耳朵疼。"],
["nose","/noʊz/","n. 鼻子","My nose is blocked.","我鼻子堵了。"],
["back","/bæk/","n. 背","My back hurts after work.","下班后我背疼。"],
["stomach","/ˈstʌmək/","n. 胃；肚子","My stomach feels strange.","我的胃不太舒服。"],
["hand","/hænd/","n. 手","Wash your hands before eating.","吃饭前洗手。"],
["leg","/leɡ/","n. 腿","I hurt my leg playing football.","我踢球伤了腿。"],
["arm","/ɑːrm/","n. 胳膊","My arm is sore.","我的胳膊酸痛。"],
["heart","/hɑːrt/","n. 心脏","Exercise is good for your heart.","锻炼对心脏有好处。"],
["blood pressure","/ˈblʌd ˌpreʃər/","n. 血压","Let me check your blood pressure.","我给你量一下血压。"],
["operation","/ˌɑːpəˈreɪʃn/","n. 手术","He needs an operation.","他需要做手术。"],
["injection","/ɪnˈdʒekʃn/","n. 打针","The doctor gave me an injection.","医生给我打了一针。"],
["vaccine","/vækˈsiːn/","n. 疫苗","Have you had the flu vaccine?","你打过流感疫苗吗？"],
["painkiller","/ˈpeɪnkɪlər/","n. 止痛药","Do you have any painkillers?","你有止痛药吗？"],
["dose","/doʊs/","n. 剂量","Don't take more than the dose.","不要超过剂量服用。"],
["gym","/dʒɪm/","n. 健身房","I go to the gym after work.","我下班后去健身房。"],
["run","/rʌn/","v. 跑步","I run every morning.","我每天早上跑步。"],
["yoga","/ˈjoʊɡə/","n. 瑜伽","I do yoga on weekends.","我周末练瑜伽。"],
["relax","/rɪˈlæks/","v. 放松","Try to relax.","试着放松一下。"],
["mental health","/ˌmentl ˈhelθ/","n. 心理健康","Mental health is very important.","心理健康非常重要。"],
["anxious","/ˈæŋkʃəs/","adj. 焦虑的","I feel anxious before interviews.","面试前我会焦虑。"],
);

const ADS = [
["advertising","/ˈædvərtaɪzɪŋ/","n. 广告业","I work in advertising.","我在广告行业工作。"],
["advertisement","/ˌædvərˈtaɪzmənt/","n. 广告","We saw your advertisement online.","我们在网上看到了你们的广告。"],
["ad","/æd/","n. 广告（简称）","This ad is very creative.","这个广告很有创意。"],
["agency","/ˈeɪdʒənsi/","n. 代理公司","We are a digital advertising agency.","我们是一家数字广告代理公司。"],
["campaign","/kæmˈpeɪn/","n. 广告活动；投放计划","The campaign starts next Monday.","这次广告活动下周一开始。"],
["advertiser","/ˈædvərtaɪzər/","n. 广告主","The advertiser wants more sales.","广告主想要更多销量。"],
["publisher","/ˈpʌblɪʃər/","n. 媒体方；发行商","We work with many publishers.","我们和很多媒体方合作。"],
["platform","/ˈplætfɔːrm/","n. 平台","Which platform works best for games?","哪个平台最适合推游戏？"],
["audience","/ˈɔːdiəns/","n. 受众","Who is our target audience?","我们的目标受众是谁？"],
["impression","/ɪmˈpreʃn/","n. 曝光（展示次数）","The ad got one million impressions.","这个广告获得了一百万次曝光。"],
["click","/klɪk/","n./v. 点击","How many clicks did we get?","我们获得了多少次点击？"],
["click-through rate","/ˌklɪk ˈθruː reɪt/","n. 点击率（CTR）","The click-through rate is two percent.","点击率是百分之二。"],
["conversion","/kənˈvɜːrʒn/","n. 转化","We need more conversions.","我们需要更多转化。"],
["conversion rate","/kənˈvɜːrʒn reɪt/","n. 转化率","The conversion rate went up this week.","这周转化率上升了。"],
["install","/ɪnˈstɔːl/","n./v. 安装","The campaign brought ten thousand installs.","这次活动带来了一万次安装。"],
["download","/ˌdaʊnˈloʊd/","v./n. 下载","Please download our app.","请下载我们的应用。"],
["user","/ˈjuːzər/","n. 用户","We have five million users.","我们有五百万用户。"],
["traffic","/ˈtræfɪk/","n. 流量","Our website traffic doubled.","我们的网站流量翻倍了。"],
["ad spend","/ˈæd spend/","n. 广告花费","Our ad spend is too high this month.","这个月我们的广告花费太高了。"],
["bid","/bɪd/","n./v. 出价","We need to raise our bid.","我们需要提高出价。"],
["cost per click","/ˌkɔːst pər ˈklɪk/","n. 单次点击成本（CPC）","What's the average cost per click?","平均单次点击成本是多少？"],
["cost per acquisition","/ˌkɔːst pər ˌækwɪˈzɪʃn/","n. 单次获客成本（CPA）","We want to lower the cost per acquisition.","我们想降低获客成本。"],
["ROI","/ˌɑːr oʊ ˈaɪ/","n. 投资回报率","What's the ROI of this campaign?","这次活动的投资回报率是多少？"],
["ROAS","/ˈroʊæs/","n. 广告支出回报率","Our ROAS is above three.","我们的广告支出回报率超过3。"],
["KPI","/ˌkeɪ piː ˈaɪ/","n. 关键绩效指标","Did we hit our KPI?","我们完成KPI了吗？"],
["metric","/ˈmetrɪk/","n. 指标","Which metrics matter most?","哪些指标最重要？"],
["data","/ˈdeɪtə/","n. 数据","Let's look at the data.","我们看看数据。"],
["analytics","/ˌænəˈlɪtɪks/","n. 数据分析","Check the analytics dashboard.","看一下数据分析面板。"],
["dashboard","/ˈdæʃbɔːrd/","n. 数据看板","The dashboard updates every hour.","数据看板每小时更新一次。"],
["performance","/pərˈfɔːrməns/","n. 表现；效果","The ad performance is great.","广告效果很好。"],
["optimize","/ˈɑːptɪmaɪz/","v. 优化","We need to optimize the campaign.","我们需要优化这次投放。"],
["optimization","/ˌɑːptəməˈzeɪʃn/","n. 优化","Optimization takes time.","优化需要时间。"],
["A/B test","/ˌeɪ ˈbiː test/","n. A/B测试","Let's run an A/B test.","我们做个A/B测试吧。"],
["test","/test/","n./v. 测试","We are still testing.","我们还在测试中。"],
["result","/rɪˈzʌlt/","n. 结果","The results look good.","结果看起来不错。"],
["creative","/kriˈeɪtɪv/","n. 广告素材 adj. 有创意的","We need new creatives this week.","这周我们需要新的素材。"],
["copy","/ˈkɑːpi/","n. 广告文案","Can you write the ad copy?","你能写一下广告文案吗？"],
["copywriter","/ˈkɑːpiraɪtər/","n. 文案（人员）","Our copywriter is very talented.","我们的文案很有才华。"],
["headline","/ˈhedlaɪn/","n. 标题","The headline is too long.","标题太长了。"],
["banner","/ˈbænər/","n. 横幅广告","Please make a new banner.","请做一个新的横幅广告。"],
["video","/ˈvɪdioʊ/","n. 视频","Video ads work better.","视频广告效果更好。"],
["image","/ˈɪmɪdʒ/","n. 图片","Please use a brighter image.","请用一张更亮的图片。"],
["design","/dɪˈzaɪn/","n./v. 设计","I like the new design.","我喜欢新的设计。"],
["designer","/dɪˈzaɪnər/","n. 设计师","The designer will send the files.","设计师会发文件过来。"],
["logo","/ˈloʊɡoʊ/","n. 标志","Make the logo bigger.","把标志放大一点。"],
["slogan","/ˈsloʊɡən/","n. 口号","We need a catchy slogan.","我们需要一个朗朗上口的口号。"],
["call to action","/ˌkɔːl tu ˈækʃn/","n. 行动号召（CTA）","Add a clear call to action.","加上一个清晰的行动号召。"],
["landing page","/ˈlændɪŋ peɪdʒ/","n. 落地页","The landing page loads too slowly.","落地页加载太慢了。"],
["website","/ˈwebsaɪt/","n. 网站","Visit our website for more information.","访问我们的网站了解更多信息。"],
["link","/lɪŋk/","n. 链接","Can you send me the link?","你能把链接发给我吗？"],
["social media","/ˌsoʊʃl ˈmiːdiə/","n. 社交媒体","We advertise on social media.","我们在社交媒体上投广告。"],
["post","/poʊst/","n./v. 帖子；发布","We post twice a day.","我们每天发两次帖子。"],
["content","/ˈkɑːntent/","n. 内容","Content is king.","内容为王。"],
["influencer","/ˈɪnfluənsər/","n. 网红；意见领袖","We hired an influencer for the launch.","我们为这次发布请了一位网红。"],
["followers","/ˈfɑːloʊərz/","n. 粉丝","She has two million followers.","她有两百万粉丝。"],
["engagement","/ɪnˈɡeɪdʒmənt/","n. 互动","Engagement is high this week.","这周互动很高。"],
["comment","/ˈkɑːment/","n./v. 评论","Read the comments under the post.","看看帖子下面的评论。"],
["share","/ʃer/","v./n. 分享；转发","Please share this post.","请转发这条帖子。"],
["viral","/ˈvaɪrəl/","adj. 病毒式传播的","The video went viral.","这个视频火了。"],
["trend","/trend/","n. 趋势","What are the latest trends?","最新的趋势是什么？"],
["awareness","/əˈwernəs/","n. 认知度","The goal is brand awareness.","目标是提升品牌认知度。"],
["exposure","/ɪkˈspoʊʒər/","n. 曝光","This event gave us a lot of exposure.","这次活动给我们带来很多曝光。"],
["reach","/riːtʃ/","n. 覆盖人数 v. 触达","The post reached one million people.","这条帖子触达了一百万人。"],
["promote","/prəˈmoʊt/","v. 推广","We want to promote our new game.","我们想推广我们的新游戏。"],
["promotion","/prəˈmoʊʃn/","n. 推广；促销","The summer promotion starts today.","夏季促销今天开始。"],
["targeting","/ˈtɑːrɡɪtɪŋ/","n. 定向","Let's change the targeting to young women.","我们把定向改成年轻女性吧。"],
["segment","/ˈseɡmənt/","n. 细分人群","This segment performs better.","这个人群效果更好。"],
["demographic","/ˌdeməˈɡræfɪk/","n. 人群特征","Our main demographic is eighteen to thirty-five.","我们的主要人群是18到35岁。"],
["region","/ˈriːdʒən/","n. 地区","Which regions should we target?","我们应该投放哪些地区？"],
["placement","/ˈpleɪsmənt/","n. 广告位","Which placement works best?","哪个广告位效果最好？"],
["inventory","/ˈɪnvəntɔːri/","n. 广告库存","The publisher has limited inventory.","媒体方的广告库存有限。"],
["programmatic","/ˌproʊɡrəˈmætɪk/","adj. 程序化的","We buy ads through programmatic platforms.","我们通过程序化平台购买广告。"],
["account manager","/əˈkaʊnt ˌmænɪdʒər/","n. 客户经理","I'm the account manager for this client.","我是这个客户的客户经理。"],
["brief","/briːf/","n. 需求简报","The client sent us a new brief.","客户给我们发了新的需求简报。"],
["pitch","/pɪtʃ/","n./v. 提案；比稿","We have a pitch tomorrow.","我们明天要去比稿。"],
["deck","/dek/","n. 演示文稿","I'll send you the deck after the meeting.","会后我把演示文稿发给你。"],
["mockup","/ˈmɑːkʌp/","n. 样稿","Here is the mockup for the new ad.","这是新广告的样稿。"],
["draft","/dræft/","n. 草稿","This is just the first draft.","这只是初稿。"],
["revise","/rɪˈvaɪz/","v. 修改","Please revise the copy.","请修改一下文案。"],
["approval","/əˈpruːvl/","n. 审核通过；批准","The ad is waiting for approval.","广告在等待审核。"],
["reject","/rɪˈdʒekt/","v. 拒绝","The platform rejected our ad.","平台拒绝了我们的广告。"],
["policy","/ˈpɑːləsi/","n. 政策","The ad violates the platform policy.","这个广告违反了平台政策。"],
["guideline","/ˈɡaɪdlaɪn/","n. 规范；指南","Please follow the brand guidelines.","请遵守品牌规范。"],
["go live","/ˌɡoʊ ˈlaɪv/","v. 上线","The campaign will go live tomorrow.","活动明天上线。"],
["pause","/pɔːz/","v. 暂停","Let's pause this ad.","我们暂停这个广告吧。"],
["scale","/skeɪl/","v. 扩量","It's working. Let's scale it up.","效果不错，我们加大投放吧。"],
["drop","/drɑːp/","v./n. 下降","Clicks dropped yesterday.","昨天点击量下降了。"],
["growth","/ɡroʊθ/","n. 增长","We saw strong growth this month.","这个月增长强劲。"],
["compare","/kəmˈper/","v. 比较","Compare this week with last week.","把这周和上周比较一下。"],
["benchmark","/ˈbentʃmɑːrk/","n. 基准","This is above the industry benchmark.","这高于行业基准。"],
["industry","/ˈɪndəstri/","n. 行业","The gaming industry is growing fast.","游戏行业增长很快。"],
["e-commerce","/ˈiː ˌkɑːmɜːrs/","n. 电商","Many of our clients are in e-commerce.","我们很多客户是做电商的。"],
["app","/æp/","n. 应用","We promote mobile apps.","我们推广手机应用。"],
["game","/ɡeɪm/","n. 游戏","This game is popular in Japan.","这款游戏在日本很受欢迎。"],
["retention","/rɪˈtenʃn/","n. 留存","Day-one retention is forty percent.","次日留存是百分之四十。"],
["lifetime value","/ˌlaɪftaɪm ˈvæljuː/","n. 用户终身价值（LTV）","We need to increase lifetime value.","我们需要提高用户终身价值。"],
["monetization","/ˌmʌnɪtəˈzeɪʃn/","n. 变现","Ad monetization is our main income.","广告变现是我们的主要收入。"],
["tracking","/ˈtrækɪŋ/","n. 追踪","Is the tracking set up correctly?","追踪设置正确吗？"],
["attribution","/ˌætrɪˈbjuːʃn/","n. 归因","We use a third-party attribution tool.","我们使用第三方归因工具。"],
["pixel","/ˈpɪksl/","n. 像素代码","Please install the pixel on your website.","请在你们的网站上安装像素代码。"],
["fraud","/frɔːd/","n. 作弊；欺诈","We found some click fraud.","我们发现了一些点击作弊。"],
["keyword","/ˈkiːwɜːrd/","n. 关键词","Add more keywords to the campaign.","给活动多加一些关键词。"],
["search","/sɜːrtʃ/","n./v. 搜索","Search ads bring high-quality users.","搜索广告带来高质量用户。"],
["localization","/ˌloʊkələˈzeɪʃn/","n. 本地化","Localization is key for overseas markets.","本地化是海外市场的关键。"],
["overseas","/ˌoʊvərˈsiːz/","adj./adv. 海外的","We help Chinese brands go overseas.","我们帮助中国品牌出海。"],
["global","/ˈɡloʊbl/","adj. 全球的","We run global campaigns.","我们做全球投放。"],
["insight","/ˈɪnsaɪt/","n. 洞察","This report gives us useful insights.","这份报告给了我们有用的洞察。"],
["recap","/ˈriːkæp/","n. 总结回顾","Here's a quick recap of last week.","这是上周的简要回顾。"],
["media plan","/ˈmiːdiə plæn/","n. 媒体投放计划","Please review the media plan.","请审阅媒体投放计划。"],
["brainstorm","/ˈbreɪnstɔːrm/","v. 头脑风暴","Let's brainstorm some ideas.","我们来头脑风暴一些点子。"],
["concept","/ˈkɑːnsept/","n. 概念；创意","I love this concept.","我很喜欢这个创意。"],
["storyboard","/ˈstɔːribɔːrd/","n. 分镜","Here's the storyboard for the video.","这是视频的分镜。"],
["shoot","/ʃuːt/","v./n. 拍摄","We will shoot the video next week.","我们下周拍视频。"],
["edit","/ˈedɪt/","v. 剪辑；编辑","Can you edit the video to fifteen seconds?","你能把视频剪到15秒吗？"],
];

const HOME = [
["apartment","/əˈpɑːrtmənt/","n. 公寓","I live in a small apartment.","我住在一套小公寓里。"],
["landlord","/ˈlændlɔːrd/","n. 房东","I need to call my landlord.","我得给房东打电话。"],
["tenant","/ˈtenənt/","n. 租客","The tenant pays rent every month.","租客每月付房租。"],
["lease","/liːs/","n. 租约","The lease is for one year.","租约是一年。"],
["roommate","/ˈruːmmeɪt/","n. 室友","My roommate is from Canada.","我的室友来自加拿大。"],
["neighbor","/ˈneɪbər/","n. 邻居","Our neighbors are very friendly.","我们的邻居很友好。"],
["furniture","/ˈfɜːrnɪtʃər/","n. 家具","We need to buy some furniture.","我们需要买些家具。"],
["kitchen","/ˈkɪtʃɪn/","n. 厨房","The kitchen is very clean.","厨房很干净。"],
["bathroom","/ˈbæθruːm/","n. 浴室；卫生间","Where is the bathroom?","卫生间在哪里？"],
["bedroom","/ˈbedruːm/","n. 卧室","It's a two-bedroom apartment.","这是一套两居室的公寓。"],
["living room","/ˈlɪvɪŋ ruːm/","n. 客厅","Let's watch TV in the living room.","我们去客厅看电视吧。"],
["balcony","/ˈbælkəni/","n. 阳台","The balcony has a great view.","阳台的视野很好。"],
["sofa","/ˈsoʊfə/","n. 沙发","The sofa is very comfortable.","沙发很舒服。"],
["chair","/tʃer/","n. 椅子","Please take a chair.","请坐。"],
["desk","/desk/","n. 书桌","My desk is next to the window.","我的书桌在窗边。"],
["lamp","/læmp/","n. 台灯","Turn on the lamp, please.","请打开台灯。"],
["light","/laɪt/","n. 灯；光","Turn off the lights when you leave.","离开时关灯。"],
["fridge","/frɪdʒ/","n. 冰箱","Put the milk in the fridge.","把牛奶放进冰箱。"],
["washing machine","/ˈwɑːʃɪŋ məˌʃiːn/","n. 洗衣机","The washing machine is broken.","洗衣机坏了。"],
["microwave","/ˈmaɪkrəweɪv/","n. 微波炉","Heat it in the microwave.","用微波炉热一下。"],
["heater","/ˈhiːtər/","n. 暖气；加热器","The heater doesn't work.","暖气不热了。"],
["shower","/ˈʃaʊər/","n. 淋浴","I take a shower every morning.","我每天早上洗澡。"],
["toilet","/ˈtɔɪlət/","n. 马桶；厕所","The toilet is blocked.","马桶堵了。"],
["sink","/sɪŋk/","n. 水槽","Put the dishes in the sink.","把碗放进水槽。"],
["trash","/træʃ/","n. 垃圾","Can you take out the trash?","你能把垃圾拿出去吗？"],
["recycle","/ˌriːˈsaɪkl/","v. 回收","We recycle plastic bottles.","我们回收塑料瓶。"],
["clean","/kliːn/","v./adj. 打扫；干净的","I clean my room every weekend.","我每周末打扫房间。"],
["wash","/wɑːʃ/","v. 洗","I need to wash my clothes.","我需要洗衣服。"],
["laundry","/ˈlɔːndri/","n. 要洗的衣服","I do laundry on Sundays.","我周日洗衣服。"],
["dishes","/ˈdɪʃɪz/","n. 碗碟","It's your turn to do the dishes.","轮到你洗碗了。"],
["repair","/rɪˈper/","v./n. 修理","Can you repair the door?","你能修一下门吗？"],
["leak","/liːk/","v./n. 漏水","The pipe is leaking.","水管漏水了。"],
["electricity","/ɪˌlekˈtrɪsəti/","n. 电","The electricity is off.","停电了。"],
["utilities","/juːˈtɪlətiz/","n. 水电煤费用","Are utilities included in the rent?","房租包含水电费吗？"],
["move","/muːv/","v. 搬家","We're moving next month.","我们下个月搬家。"],
["key","/kiː/","n. 钥匙","I lost my keys.","我把钥匙弄丢了。"],
["lock","/lɑːk/","v./n. 锁","Did you lock the door?","你锁门了吗？"],
["package","/ˈpækɪdʒ/","n. 包裹","I'm waiting for a package.","我在等一个包裹。"],
["mail","/meɪl/","n. 信件","Did we get any mail today?","我们今天收到信件了吗？"],
["grocery","/ˈɡroʊsəri/","n. 食品杂货","I need to buy groceries.","我需要买些日用食品。"],
["get up","/ˌɡet ˈʌp/","v. 起床","I get up at seven.","我七点起床。"],
["wake up","/ˌweɪk ˈʌp/","v. 醒来","I woke up late today.","我今天醒晚了。"],
["alarm","/əˈlɑːrm/","n. 闹钟","I didn't hear my alarm.","我没听到闹钟。"],
["brush","/brʌʃ/","v. 刷","Brush your teeth before bed.","睡前刷牙。"],
["get dressed","/ˌɡet ˈdrest/","穿衣服","Hurry up and get dressed.","快点穿好衣服。"],
["commute","/kəˈmjuːt/","v./n. 通勤","My commute takes an hour.","我通勤要一个小时。"],
["pet","/pet/","n. 宠物","Do you have any pets?","你养宠物吗？"],
["dog","/dɔːɡ/","n. 狗","I walk my dog every evening.","我每天傍晚遛狗。"],
["cat","/kæt/","n. 猫","My cat sleeps all day.","我的猫整天睡觉。"],
["garden","/ˈɡɑːrdn/","n. 花园","We grow vegetables in the garden.","我们在花园里种菜。"],
["quiet","/ˈkwaɪət/","adj. 安静的","This neighborhood is very quiet.","这个街区很安静。"],
["comfortable","/ˈkʌmftəbl/","adj. 舒适的","The bed is very comfortable.","床很舒服。"],
["convenient","/kənˈviːniənt/","adj. 方便的","The location is very convenient.","位置很方便。"],
["messy","/ˈmesi/","adj. 乱的","My room is so messy.","我的房间好乱。"],
];

const SOCIAL = [
["hobby","/ˈhɑːbi/","n. 爱好","What are your hobbies?","你有什么爱好？"],
["interested","/ˈɪntrəstɪd/","adj. 感兴趣的","I'm interested in photography.","我对摄影感兴趣。"],
["favorite","/ˈfeɪvərɪt/","adj. 最喜欢的","What's your favorite food?","你最喜欢的食物是什么？"],
["enjoy","/ɪnˈdʒɔɪ/","v. 享受；喜欢","I enjoy cooking.","我喜欢做饭。"],
["hang out","/ˌhæŋ ˈaʊt/","v. 一起玩","Do you want to hang out this weekend?","这周末想一起出去玩吗？"],
["party","/ˈpɑːrti/","n. 聚会","Are you coming to the party?","你来参加聚会吗？"],
["birthday","/ˈbɜːrθdeɪ/","n. 生日","Happy birthday!","生日快乐！"],
["invitation","/ˌɪnvɪˈteɪʃn/","n. 邀请","Thanks for the invitation.","谢谢你的邀请。"],
["celebrate","/ˈselɪbreɪt/","v. 庆祝","Let's celebrate!","我们庆祝一下吧！"],
["congratulations","/kənˌɡrætʃəˈleɪʃnz/","int. 恭喜","Congratulations on your new job!","恭喜你找到新工作！"],
["fun","/fʌn/","n./adj. 乐趣；有趣的","That sounds like fun.","听起来很有趣。"],
["funny","/ˈfʌni/","adj. 好笑的","He's really funny.","他真的很幽默。"],
["interesting","/ˈɪntrəstɪŋ/","adj. 有趣的","That's interesting.","那很有意思。"],
["boring","/ˈbɔːrɪŋ/","adj. 无聊的","The movie was boring.","那部电影很无聊。"],
["amazing","/əˈmeɪzɪŋ/","adj. 令人惊叹的","That's amazing!","太棒了！"],
["awesome","/ˈɔːsəm/","adj. 太棒了","Awesome, thanks!","太好了，谢谢！"],
["excited","/ɪkˈsaɪtɪd/","adj. 兴奋的","I'm so excited about the trip.","我对这次旅行好兴奋。"],
["nervous","/ˈnɜːrvəs/","adj. 紧张的","I'm nervous about my speech.","我对演讲很紧张。"],
["worried","/ˈwɜːrid/","adj. 担心的","Don't be worried.","别担心。"],
["surprised","/sərˈpraɪzd/","adj. 惊讶的","I was surprised to see him.","见到他我很惊讶。"],
["angry","/ˈæŋɡri/","adj. 生气的","Are you angry with me?","你在生我的气吗？"],
["upset","/ʌpˈset/","adj. 不高兴的","She looks upset.","她看起来不高兴。"],
["glad","/ɡlæd/","adj. 高兴的","I'm glad you came.","很高兴你来了。"],
["miss","/mɪs/","v. 想念；错过","I miss you.","我想你。"],
["remember","/rɪˈmembər/","v. 记得","Do you remember me?","你还记得我吗？"],
["forget","/fərˈɡet/","v. 忘记","Don't forget to call me.","别忘了给我打电话。"],
["hope","/hoʊp/","v. 希望","I hope you like it.","希望你喜欢。"],
["guess","/ɡes/","v. 猜","Guess what?","你猜怎么着？"],
["mean","/miːn/","v. 意思是","What do you mean?","你是什么意思？"],
["joke","/dʒoʊk/","n. 玩笑","It's just a joke.","只是开个玩笑。"],
["chat","/tʃæt/","v./n. 聊天","Let's chat later.","我们回头再聊。"],
["message","/ˈmesɪdʒ/","n. 消息","I'll send you a message.","我给你发消息。"],
["text","/tekst/","v. 发短信","Text me when you get home.","到家了给我发个消息。"],
["number","/ˈnʌmbər/","n. 号码","Can I have your number?","能给我你的号码吗？"],
["meet","/miːt/","v. 见面","Where should we meet?","我们在哪见面？"],
["date","/deɪt/","n. 日期；约会","What's the date today?","今天几号？"],
["age","/eɪdʒ/","n. 年龄","We are the same age.","我们同岁。"],
["married","/ˈmærid/","adj. 已婚的","Are you married?","你结婚了吗？"],
["single","/ˈsɪŋɡl/","adj. 单身的","I'm still single.","我还是单身。"],
["kids","/kɪdz/","n. 孩子们","Do you have kids?","你有孩子吗？"],
["hometown","/ˈhoʊmtaʊn/","n. 家乡","My hometown is a small city.","我的家乡是个小城市。"],
["born","/bɔːrn/","adj. 出生","I was born in Guangzhou.","我出生在广州。"],
["grow up","/ˌɡroʊ ˈʌp/","v. 长大","Where did you grow up?","你在哪里长大的？"],
["live","/lɪv/","v. 住；生活","Where do you live?","你住在哪里？"],
["sport","/spɔːrt/","n. 运动","What sports do you like?","你喜欢什么运动？"],
["travel","/ˈtrævl/","v./n. 旅行","I love to travel.","我喜欢旅行。"],
["song","/sɔːŋ/","n. 歌","This is my favorite song.","这是我最喜欢的歌。"],
["dance","/dæns/","v. 跳舞","Do you like to dance?","你喜欢跳舞吗？"],
["sing","/sɪŋ/","v. 唱歌","Let's sing karaoke tonight.","我们今晚去唱K吧。"],
["agree","/əˈɡriː/","v. 同意","I totally agree.","我完全同意。"],
["of course","/əv ˈkɔːrs/","当然","Of course you can.","你当然可以。"],
["actually","/ˈæktʃuəli/","adv. 实际上","Actually, I'm not sure.","其实我也不确定。"],
["probably","/ˈprɑːbəbli/","adv. 可能","I'll probably be late.","我可能会迟到。"],
["anyway","/ˈeniweɪ/","adv. 不管怎样","Anyway, let's go.","不管怎样，我们走吧。"],
["kind","/kaɪnd/","adj. 友善的","You are so kind.","你真好。"],
["polite","/pəˈlaɪt/","adj. 有礼貌的","Be polite to everyone.","对每个人都要有礼貌。"],
];

// [词根/词缀, 含义, [[单词, 拆解, 中文], ...]]
const ROOTS = [
["re-","再；回",[["return","re 回 + turn 转","返回"],["review","re 再 + view 看","复习"],["replay","re 再 + play 播放","重播"],["refund","re 回 + fund 钱","退款"]]],
["un-","不",[["unhappy","un 不 + happy 开心","不开心的"],["unknown","un 不 + known 知道的","未知的"],["unable","un 不 + able 能","不能的"],["unfair","un 不 + fair 公平","不公平的"]]],
["dis-","不；相反；去掉",[["dislike","dis 不 + like 喜欢","不喜欢"],["disagree","dis 不 + agree 同意","不同意"],["disappear","dis 相反 + appear 出现","消失"],["discount","dis 去掉 + count 计算","折扣"]]],
["in- / im-","不",[["impossible","im 不 + possible 可能的","不可能的"],["incorrect","in 不 + correct 正确的","不正确的"],["invisible","in 不 + visible 看得见的","看不见的"],["impolite","im 不 + polite 礼貌的","不礼貌的"]]],
["mis-","错误",[["mistake","mis 错 + take 拿","错误"],["misunderstand","mis 错 + understand 理解","误解"],["mislead","mis 错 + lead 引导","误导"],["misspell","mis 错 + spell 拼写","拼错"]]],
["pre-","前；预先",[["preview","pre 预先 + view 看","预览"],["prepay","pre 预先 + pay 付","预付"],["predict","pre 预先 + dict 说","预测"],["prepare","pre 预先 + pare 准备","准备"]]],
["ex-","出；向外",[["export","ex 出 + port 运","出口"],["exit","ex 出 + it 走","出口"],["exclude","ex 出 + clude 关","排除"],["expand","ex 向外 + pand 展开","扩大"]]],
["in- / im-（进入）","进入；向内",[["import","im 进 + port 运","进口"],["income","in 进 + come 来","收入"],["input","in 进 + put 放","输入"],["insight","in 内 + sight 看","洞察"]]],
["trans-","跨越；转移",[["transfer","trans 转 + fer 带","转账；转移"],["translate","trans 转 + late 带","翻译"],["transport","trans 跨 + port 运","运输"],["transform","trans 转 + form 形","转变"]]],
["inter-","之间；相互",[["international","inter 之间 + national 国家的","国际的"],["internet","inter 相互 + net 网","互联网"],["interview","inter 相互 + view 看","面试"],["interact","inter 相互 + act 行动","互动"]]],
["sub-","下面",[["subway","sub 下 + way 路","地铁"],["submit","sub 下 + mit 送","提交"],["subscribe","sub 下 + scribe 写（签名）","订阅"],["subtitle","sub 下 + title 标题","字幕"]]],
["over-","超过；在上",[["overweight","over 超过 + weight 重量","超重的"],["overdue","over 超过 + due 到期","逾期的"],["overseas","over 越过 + seas 海","海外的"],["overtime","over 超过 + time 时间","加班"]]],
["co- / con- / com-","共同；一起",[["cooperate","co 共同 + operate 操作","合作"],["connect","con 一起 + nect 连接","连接"],["combine","com 一起 + bine 二","结合"],["colleague","col 共同 + league 联盟","同事"]]],
["de-","向下；去除；离开",[["decrease","de 下 + crease 增长","减少"],["depart","de 离开 + part 分开","出发"],["decline","de 下 + cline 倾斜","下降"],["defrost","de 去除 + frost 霜","解冻"]]],
["tele-","远",[["telephone","tele 远 + phone 声音","电话"],["television","tele 远 + vision 看","电视"],["telescope","tele 远 + scope 看","望远镜"],["telework","tele 远 + work 工作","远程办公"]]],
["multi-","多",[["multiple","multi 多 + ple 倍","多个的"],["multimedia","multi 多 + media 媒体","多媒体"],["multinational","multi 多 + national 国家的","跨国的"],["multitask","multi 多 + task 任务","同时做多件事"]]],
["uni- / bi- / tri-","一 / 二 / 三",[["uniform","uni 一 + form 样式","制服"],["unique","uni 一 + que","独一无二的"],["bilingual","bi 双 + lingual 语言的","双语的"],["triangle","tri 三 + angle 角","三角形"]]],
["auto-","自己；自动",[["automatic","auto 自己 + matic 动","自动的"],["autopilot","auto 自动 + pilot 驾驶员","自动驾驶"],["automobile","auto 自己 + mobile 移动","汽车"],["autograph","auto 自己 + graph 写","亲笔签名"]]],
["port","搬运；携带；港口",[["transport","trans 跨 + port 运","运输"],["portable","port 携带 + able 能","便携的"],["report","re 回 + port 带","报告"],["passport","pass 通过 + port 港口","护照"]]],
["vis / vid","看",[["visit","vis 看 + it 走","参观；拜访"],["vision","vis 看 + ion","视力；愿景"],["video","vid 看 + eo","视频"],["revise","re 再 + vise 看","修改"]]],
["spect","看",[["inspect","in 内 + spect 看","检查"],["expect","ex 出 + spect 看","期待"],["respect","re 再 + spect 看","尊重"],["prospect","pro 向前 + spect 看","前景"]]],
["dict","说",[["dictionary","dict 说 + ionary","词典"],["predict","pre 预先 + dict 说","预测"],["dictate","dict 说 + ate","口述"],["contradict","contra 反 + dict 说","反驳"]]],
["scrib / script","写",[["describe","de 向下 + scribe 写","描述"],["subscribe","sub 下 + scribe 写","订阅"],["script","script 写","脚本；剧本"],["prescription","pre 预先 + script 写","处方"]]],
["duc / duct","引导",[["produce","pro 向前 + duce 引","生产"],["product","pro 向前 + duct 引","产品"],["introduce","intro 向内 + duce 引","介绍"],["reduce","re 回 + duce 引","减少"]]],
["form","形状；形式",[["format","form 形 + at","格式"],["inform","in 进 + form 形","通知"],["perform","per 完全 + form 形","表演；表现"],["platform","plat 平 + form 形","平台"]]],
["mit / miss","送；放出",[["submit","sub 下 + mit 送","提交"],["mission","miss 送 + ion","任务"],["transmit","trans 跨 + mit 送","传输"],["admit","ad 向 + mit 送","承认"]]],
["pos / pon","放置",[["position","pos 放 + ition","位置；职位"],["deposit","de 下 + posit 放","存款"],["postpone","post 后 + pone 放","推迟"],["expose","ex 出 + pose 放","曝光"]]],
["tract","拉",[["attract","at 向 + tract 拉","吸引"],["contract","con 共同 + tract 拉","合同"],["distract","dis 分开 + tract 拉","分散注意力"],["tractor","tract 拉 + or 物","拖拉机"]]],
["vert / vers","转",[["advertise","ad 向 + vert 转","做广告（让人转过来看）"],["convert","con 完全 + vert 转","转化"],["reverse","re 回 + verse 转","反转"],["version","vers 转 + ion","版本"]]],
["cred","相信",[["credit","cred 信 + it","信用"],["credible","cred 信 + ible 可…的","可信的"],["incredible","in 不 + cred 信 + ible","难以置信的"],["credit card","credit 信用 + card 卡","信用卡"]]],
["fin","结束；界限",[["finish","fin 结束 + ish","完成"],["final","fin 结束 + al","最后的"],["finance","fin 结清 + ance","财务"],["infinite","in 不 + fin 界限 + ite","无限的"]]],
["count","计算",[["account","ac 向 + count 计算","账户"],["accountant","account 账 + ant 人","会计"],["discount","dis 去掉 + count 计算","折扣"],["counter","count 计算 + er 物","柜台"]]],
["cap / cept","拿；抓",[["accept","ac 向 + cept 拿","接受"],["except","ex 出 + cept 拿","除了"],["concept","con 一起 + cept 抓","概念"],["capture","capt 抓 + ure","捕获"]]],
["struct","建造",[["structure","struct 建 + ure","结构"],["construct","con 一起 + struct 建","建造"],["instruction","in 内 + struct 建 + ion","说明；指令"],["infrastructure","infra 下 + structure 结构","基础设施"]]],
["sign","标记",[["signal","sign 标记 + al","信号"],["design","de 向下 + sign 标记","设计"],["signature","sign 标记 + ature","签名"],["assign","as 向 + sign 标记","分配"]]],
["graph","写；画",[["photograph","photo 光 + graph 画","照片"],["paragraph","para 旁边 + graph 写","段落"],["graphic","graph 画 + ic","图形的"],["biography","bio 生命 + graphy 写","传记"]]],
["phon","声音",[["phone","phon 声音","电话"],["microphone","micro 小 + phone 声音","麦克风"],["headphones","head 头 + phones 声音","耳机"],["symphony","sym 共同 + phony 声音","交响乐"]]],
["-able / -ible","能…的；可…的",[["available","avail 有用 + able","可用的；有空的"],["affordable","afford 负担 + able","买得起的"],["readable","read 读 + able","易读的"],["visible","vis 看 + ible","看得见的"]]],
["-er / -or / -ist","…的人",[["designer","design 设计 + er","设计师"],["investor","invest 投资 + or","投资者"],["advertiser","advertise 做广告 + er","广告主"],["tourist","tour 旅游 + ist","游客"]]],
["-tion / -sion","名词：行为或结果",[["decision","decide 决定 + sion","决定"],["promotion","promote 推广 + tion","推广；升职"],["conversion","convert 转化 + sion","转化"],["reservation","reserve 预订 + ation","预订"]]],
["-ment","名词：行为或结果",[["payment","pay 付 + ment","付款"],["agreement","agree 同意 + ment","协议"],["advertisement","advertise 做广告 + ment","广告"],["department","depart 分开 + ment","部门"]]],
["-ful","充满…的",[["helpful","help 帮助 + ful","有帮助的"],["successful","success 成功 + ful","成功的"],["careful","care 小心 + ful","仔细的"],["useful","use 用 + ful","有用的"]]],
["-less","没有…的",[["useless","use 用 + less","没用的"],["careless","care 小心 + less","粗心的"],["wireless","wire 线 + less","无线的"],["homeless","home 家 + less","无家可归的"]]],
["-ize","使…化",[["optimize","optim 最佳 + ize","优化"],["localize","local 本地 + ize","本地化"],["organize","organ 器官/组织 + ize","组织"],["realize","real 真实 + ize","意识到；实现"]]],
["-ly","…地（副词）",[["quickly","quick 快 + ly","快速地"],["slowly","slow 慢 + ly","慢慢地"],["finally","final 最后 + ly","最终"],["usually","usual 通常 + ly","通常"]]],
];
