// 原创课文。只能在末尾追加，课号即数组下标，改顺序会打乱学习记录。
// lines: [说话人(短文为空), 英文, 中文]   words: [单词, 音标, 中文]
const LESSONS = [
{ level: 1, title: "Excuse me!", cn: "打扰一下！", point: "一般疑问句：把 is 放到句首。This is your bag. → Is this your bag?",
  lines: [
["Amy","Excuse me.","打扰一下。"],
["Mark","Yes?","什么事？"],
["Amy","Is this your bag?","这是你的包吗？"],
["Mark","Let me see. Yes, it is.","我看看。是的，是我的。"],
["Amy","It was on the seat.","它刚才在座位上。"],
["Mark","Thank you very much!","非常感谢！"],
["Amy","You're welcome.","不客气。"],
  ],
  words: [["excuse","/ɪkˈskjuːz/","v. 原谅；打扰"],["bag","/bæɡ/","n. 包"],["see","/siː/","v. 看"],["seat","/siːt/","n. 座位"],["welcome","/ˈwelkəm/","adj. 受欢迎的"]] },

{ level: 1, title: "Nice to meet you", cn: "很高兴认识你", point: "介绍别人用 This is…；I'm 是 I am 的缩写。",
  lines: [
["Lisa","Good morning, Tom. This is Anna.","早上好，汤姆。这是安娜。"],
["Lisa","She is our new designer.","她是我们的新设计师。"],
["Tom","Hello, Anna. Nice to meet you.","你好，安娜。很高兴认识你。"],
["Anna","Nice to meet you too.","我也很高兴认识你。"],
["Tom","Where are you from?","你是哪里人？"],
["Anna","I'm from Shanghai.","我来自上海。"],
["Tom","Welcome to the team!","欢迎加入团队！"],
  ],
  words: [["meet","/miːt/","v. 遇见；认识"],["new","/nuː/","adj. 新的"],["designer","/dɪˈzaɪnər/","n. 设计师"],["from","/frʌm/","prep. 来自"],["team","/tiːm/","n. 团队"]] },

{ level: 1, title: "At the hotel", cn: "在酒店", point: "May I…? 礼貌地请求许可；Here you are. 是递东西给别人时说的「给你」。",
  lines: [
["Receptionist","Good evening. Can I help you?","晚上好。有什么可以帮您？"],
["Guest","Yes. I have a reservation. My name is Li Wei.","是的。我有预订。我叫李伟。"],
["Receptionist","Let me check. Yes, a single room for three nights.","我查一下。是的，单人间，住三晚。"],
["Receptionist","May I see your passport, please?","请出示您的护照。"],
["Guest","Here you are.","给你。"],
["Receptionist","Thank you. Your room is 708. Here is your key card.","谢谢。您的房间是708。这是您的房卡。"],
["Guest","What time is breakfast?","早餐几点？"],
["Receptionist","From seven to ten, on the second floor.","七点到十点，在二楼。"],
["Guest","Great, thanks.","太好了，谢谢。"],
  ],
  words: [["evening","/ˈiːvnɪŋ/","n. 晚上"],["reservation","/ˌrezərˈveɪʃn/","n. 预订"],["check","/tʃek/","v. 查看"],["passport","/ˈpæspɔːrt/","n. 护照"],["key card","/ˈkiː kɑːrd/","n. 房卡"],["floor","/flɔːr/","n. 楼层"]] },

{ level: 1, title: "What's the weather like?", cn: "天气怎么样？", point: "What's … like? 用来问「……怎么样」。What's the weather like? 天气怎么样？",
  lines: [
["Mia","What's the weather like in London today?","今天伦敦天气怎么样？"],
["Ben","It's cold and rainy.","又冷又下雨。"],
["Mia","Really? It's sunny and warm here in Bangkok.","真的吗？曼谷这里阳光明媚，很暖和。"],
["Ben","Lucky you!","你真幸运！"],
["Mia","Don't forget your umbrella.","别忘了带伞。"],
["Ben","Don't worry. It's always in my bag.","别担心，它一直在我包里。"],
  ],
  words: [["weather","/ˈweðər/","n. 天气"],["rainy","/ˈreɪni/","adj. 下雨的"],["sunny","/ˈsʌni/","adj. 晴朗的"],["warm","/wɔːrm/","adj. 温暖的"],["lucky","/ˈlʌki/","adj. 幸运的"],["umbrella","/ʌmˈbrelə/","n. 雨伞"]] },

{ level: 1, title: "Ordering coffee", cn: "点咖啡", point: "Can I have …, please? 是点餐、要东西最常用的句型。",
  lines: [
["Barista","Hi! What can I get for you?","你好！想要点什么？"],
["Customer","Can I have a large latte, please?","请给我一杯大杯拿铁。"],
["Barista","Sure. Hot or iced?","好的。热的还是冰的？"],
["Customer","Iced, please. And no sugar.","冰的，谢谢。不要糖。"],
["Barista","For here or to go?","在这里喝还是带走？"],
["Customer","To go, please. How much is it?","带走。多少钱？"],
["Barista","That's four fifty.","四块五。"],
["Customer","Can I pay by card?","可以刷卡吗？"],
["Barista","Of course.","当然可以。"],
  ],
  words: [["large","/lɑːrdʒ/","adj. 大的"],["latte","/ˈlɑːteɪ/","n. 拿铁"],["iced","/aɪst/","adj. 加冰的"],["sugar","/ˈʃʊɡər/","n. 糖"],["to go","/tə ˈɡoʊ/","带走"],["card","/kɑːrd/","n. 卡"]] },

{ level: 1, title: "Asking the way", cn: "问路", point: "祈使句以动词开头，表示指示或请求：Go straight. Turn left.",
  lines: [
["Tourist","Excuse me. How do I get to the museum?","打扰一下，去博物馆怎么走？"],
["Local","Go straight along this street.","沿着这条街直走。"],
["Local","Turn left at the second traffic light.","在第二个红绿灯左转。"],
["Local","The museum is on your right.","博物馆就在你右手边。"],
["Tourist","Is it far?","远吗？"],
["Local","No, it's about ten minutes on foot.","不远，走路大约十分钟。"],
["Tourist","Thank you so much.","太感谢了。"],
  ],
  words: [["museum","/mjuˈziːəm/","n. 博物馆"],["straight","/streɪt/","adv. 笔直地"],["along","/əˈlɔːŋ/","prep. 沿着"],["turn","/tɜːrn/","v. 转弯"],["traffic light","/ˈtræfɪk laɪt/","n. 红绿灯"],["far","/fɑːr/","adj. 远的"]] },

{ level: 1, title: "A busy Monday", cn: "忙碌的周一", point: "一般现在时描述习惯。主语是 he / she / it 时，动词加 s：she works, she reads。",
  lines: [
["","Anna works at an advertising agency.","安娜在一家广告公司工作。"],
["","Every Monday is very busy for her.","每个周一对她来说都很忙。"],
["","She gets to the office at nine.","她九点到办公室。"],
["","First, she reads her emails.","首先，她看邮件。"],
["","Then she has a team meeting at ten.","然后她十点开团队会议。"],
["","In the afternoon, she designs new ads for clients.","下午，她为客户设计新广告。"],
["","She usually finishes work at six.","她通常六点下班。"],
  ],
  words: [["agency","/ˈeɪdʒənsi/","n. 代理公司"],["busy","/ˈbɪzi/","adj. 忙的"],["first","/fɜːrst/","adv. 首先"],["then","/ðen/","adv. 然后"],["client","/ˈklaɪənt/","n. 客户"],["usually","/ˈjuːʒuəli/","adv. 通常"],["finish","/ˈfɪnɪʃ/","v. 完成；结束"]] },

{ level: 1, title: "Where's my phone?", cn: "我的手机在哪？", point: "表示位置的介词：on 在上面，in 在里面，under 在下面。",
  lines: [
["Tom","Have you seen my phone?","你看到我的手机了吗？"],
["Lisa","Is it on your desk?","在你桌上吗？"],
["Tom","No, it isn't.","不在。"],
["Lisa","Is it in your bag?","在你包里吗？"],
["Tom","I looked. It's not there.","我看过了，不在那里。"],
["Lisa","Let me call it. Listen!","我打一下。听！"],
["Tom","Oh, it's under my jacket!","噢，在我外套下面！"],
["Lisa","You always do that!","你总是这样！"],
  ],
  words: [["phone","/foʊn/","n. 手机"],["desk","/desk/","n. 书桌"],["under","/ˈʌndər/","prep. 在……下面"],["jacket","/ˈdʒækɪt/","n. 外套"],["listen","/ˈlɪsn/","v. 听"],["always","/ˈɔːlweɪz/","adv. 总是"]] },

{ level: 1, title: "Shopping for a gift", cn: "买礼物", point: "too + 形容词，表示「太……了」：too expensive 太贵了，too big 太大了。",
  lines: [
["Assistant","Can I help you?","需要帮忙吗？"],
["Mia","Yes. I'm looking for a gift for my mother.","是的。我在给我妈妈找一份礼物。"],
["Assistant","How about this scarf? It's very popular.","这条围巾怎么样？很受欢迎。"],
["Mia","It's beautiful, but it's too expensive.","很漂亮，但是太贵了。"],
["Assistant","This one is on sale. It's only thirty dollars.","这条在打折，只要三十美元。"],
["Mia","I like the color. I'll take it.","我喜欢这个颜色。我买了。"],
["Assistant","Would you like me to wrap it?","需要我帮您包起来吗？"],
["Mia","Yes, please.","好的，谢谢。"],
  ],
  words: [["look for","/ˈlʊk fɔːr/","寻找"],["gift","/ɡɪft/","n. 礼物"],["scarf","/skɑːrf/","n. 围巾"],["popular","/ˈpɑːpjələr/","adj. 受欢迎的"],["on sale","/ɑːn ˈseɪl/","打折"],["wrap","/ræp/","v. 包装"]] },

{ level: 1, title: "Last weekend", cn: "上周末", point: "一般过去时：规则动词加 -ed（stay → stayed），不规则动词要单独记（go → went，swim → swam）。",
  lines: [
["Ben","How was your weekend?","你周末过得怎么样？"],
["Anna","It was great. I went to the beach with my friends.","很棒。我和朋友去海边了。"],
["Ben","Sounds fun! What did you do there?","听起来很好玩！你们在那里做了什么？"],
["Anna","We swam in the sea and had a barbecue.","我们在海里游泳，还吃了烧烤。"],
["Anna","What about you?","你呢？"],
["Ben","I stayed at home and watched movies.","我待在家里看电影。"],
["Ben","I was too tired to go out.","我太累了，不想出门。"],
  ],
  words: [["weekend","/ˈwiːkend/","n. 周末"],["went","/went/","v. 去（go 的过去式）"],["beach","/biːtʃ/","n. 海滩"],["swam","/swæm/","v. 游泳（swim 的过去式）"],["barbecue","/ˈbɑːrbɪkjuː/","n. 烧烤"],["stayed","/steɪd/","v. 待（stay 的过去式）"]] },

{ level: 2, title: "A missed flight", cn: "误了航班", point: "过去进行时 was / were + 动词-ing，表示过去某个时刻正在发生的事：the plane was taking off（飞机正在起飞）。",
  lines: [
["","Last month, I flew to Singapore for a business meeting.","上个月，我飞去新加坡开一个商务会议。"],
["","My flight was at eight in the morning.","我的航班是早上八点的。"],
["","I woke up at six, but there was heavy traffic on the way to the airport.","我六点就醒了，但去机场的路上堵车很严重。"],
["","When I arrived, the plane was already taking off.","我到的时候，飞机已经在起飞了。"],
["","I was very worried because the meeting was the next day.","我非常着急，因为会议就在第二天。"],
["","Luckily, the airline put me on the next flight.","幸运的是，航空公司给我改签了下一班。"],
["","I arrived late at night, tired but happy.","我深夜才到，很累，但很开心。"],
["","Now I always leave home three hours early.","现在我总是提前三个小时出门。"],
  ],
  words: [["flew","/fluː/","v. 飞（fly 的过去式）"],["heavy","/ˈhevi/","adj. 大量的；重的"],["arrive","/əˈraɪv/","v. 到达"],["already","/ɔːlˈredi/","adv. 已经"],["worried","/ˈwɜːrid/","adj. 担心的"],["luckily","/ˈlʌkɪli/","adv. 幸运地"],["airline","/ˈerlaɪn/","n. 航空公司"]] },

{ level: 2, title: "The best idea", cn: "最好的点子", point: "比较级和最高级：simple → simpler → simplest；good → better → best；quiet → quieter → quietest。",
  lines: [
["","Our team had a big pitch last week.","我们团队上周有一个重要的比稿。"],
["","The client was a famous sports brand.","客户是一个知名运动品牌。"],
["","We needed a new idea for their summer campaign.","我们需要为他们的夏季活动想一个新点子。"],
["","Everyone gave ideas, but none of them were exciting.","每个人都提了想法，但没有一个让人兴奋。"],
["","Then our intern, Sam, said quietly, \"What about real people instead of stars?\"","然后我们的实习生萨姆小声说：「用普通人代替明星怎么样？」"],
["","It was the simplest idea, but also the best one.","这是最简单的点子，但也是最好的。"],
["","The client loved it, and we won the project.","客户非常喜欢，我们拿下了这个项目。"],
["","Sometimes the best ideas come from the quietest people.","有时候最好的点子来自最安静的人。"],
  ],
  words: [["pitch","/pɪtʃ/","n. 比稿；提案"],["famous","/ˈfeɪməs/","adj. 著名的"],["campaign","/kæmˈpeɪn/","n. 广告活动"],["none","/nʌn/","pron. 没有一个"],["intern","/ˈɪntɜːrn/","n. 实习生"],["instead of","/ɪnˈsted əv/","代替"],["won","/wʌn/","v. 赢得（win 的过去式）"]] },

{ level: 2, title: "Lost in Tokyo", cn: "在东京迷路", point: "Could you …? 比 Can you …? 更礼貌，向陌生人求助时用：Could you help me, please?",
  lines: [
["","On my first day in Tokyo, I wanted to visit a famous temple.","在东京的第一天，我想去参观一座有名的寺庙。"],
["","I took the subway, but I got off at the wrong station.","我坐了地铁，但在错误的站下了车。"],
["","My phone was out of battery, so I couldn't use the map.","我的手机没电了，所以没法用地图。"],
["","I stopped an old man and asked, \"Could you help me, please?\"","我拦住一位老先生，问道：「您能帮帮我吗？」"],
["","He didn't speak much English, but he smiled and said, \"Follow me.\"","他英语说得不多，但他笑着说：「跟我来。」"],
["","He walked with me for twenty minutes, all the way to the temple.","他陪我走了二十分钟，一直把我送到寺庙。"],
["","I said thank you many times.","我说了很多次谢谢。"],
["","Kind people make a trip unforgettable.","善良的人让一次旅行难以忘怀。"],
  ],
  words: [["temple","/ˈtempl/","n. 寺庙"],["got off","/ˌɡɑːt ˈɔːf/","下车（get off 的过去式）"],["wrong","/rɔːŋ/","adj. 错误的"],["battery","/ˈbætəri/","n. 电池"],["smiled","/smaɪld/","v. 微笑（smile 的过去式）"],["follow","/ˈfɑːloʊ/","v. 跟随"],["unforgettable","/ˌʌnfərˈɡetəbl/","adj. 难忘的"]] },

{ level: 2, title: "The numbers don't lie", cn: "数字不会说谎", point: "现在完成时 have / has + 过去分词，表示过去发生、影响持续到现在：We have stopped those ads（我们已经停了那些广告）。",
  lines: [
["","Our client has spent a lot of money on video ads this year.","我们的客户今年在视频广告上花了很多钱。"],
["","But last month, their sales went down.","但上个月，他们的销售额下降了。"],
["","The client was angry and called my manager.","客户很生气，给我经理打了电话。"],
["","My manager asked me to check the data.","经理让我检查数据。"],
["","I found that most of the clicks came from one country.","我发现大部分点击来自一个国家。"],
["","Many of them were fake clicks.","其中很多是虚假点击。"],
["","We have stopped those ads and changed the targeting.","我们已经停掉了那些广告，并修改了定向。"],
["","Since then, the results have improved a lot.","从那以后，效果改善了很多。"],
  ],
  words: [["spent","/spent/","v. 花费（spend 的过去式）"],["went down","/ˌwent ˈdaʊn/","下降（go down 的过去式）"],["data","/ˈdeɪtə/","n. 数据"],["fake","/feɪk/","adj. 假的"],["targeting","/ˈtɑːrɡɪtɪŋ/","n. 定向"],["since","/sɪns/","prep. 自从"],["improved","/ɪmˈpruːvd/","v. 改善（improve 的过去分词）"]] },

{ level: 2, title: "A cooking disaster", cn: "做饭灾难", point: "while + 过去进行时：「正在……的时候」，另一件事突然发生：While the fish was cooking, my phone rang.",
  lines: [
["","Last Saturday, I invited some colleagues to my apartment for dinner.","上周六，我邀请几个同事到我的公寓吃晚饭。"],
["","I wanted to cook a fish, just like my mother does.","我想做一条鱼，就像我妈妈做的那样。"],
["","While the fish was cooking, my phone rang.","鱼正在做的时候，我的电话响了。"],
["","It was my boss, and the call was long.","是我老板打来的，电话打了很久。"],
["","Suddenly, I smelled smoke.","突然，我闻到了烟味。"],
["","The fish was black!","鱼烧黑了！"],
["","When my guests arrived, the kitchen was full of smoke.","客人到的时候，厨房里全是烟。"],
["","In the end, we ordered pizza and laughed all night.","最后，我们点了比萨，笑了一整晚。"],
  ],
  words: [["invited","/ɪnˈvaɪtɪd/","v. 邀请（invite 的过去式）"],["colleague","/ˈkɑːliːɡ/","n. 同事"],["rang","/ræŋ/","v. 响（ring 的过去式）"],["suddenly","/ˈsʌdənli/","adv. 突然"],["smoke","/smoʊk/","n. 烟"],["guest","/ɡest/","n. 客人"],["laughed","/læft/","v. 笑（laugh 的过去式）"]] },

{ level: 2, title: "A new start", cn: "新的开始", point: "be going to + 动词，表示打算做某事：I'm going to study English every day.",
  lines: [
["","I'm thirty-two, and my English is not very good.","我三十二岁，英语不太好。"],
["","I learned English at school, but I've forgotten most of it.","我在学校学过英语，但大部分都忘了。"],
["","At work, I often need to talk to foreign clients.","工作中，我经常需要和外国客户交流。"],
["","Sometimes I understand them, but I can't answer well.","有时我能听懂他们，但回答不好。"],
["","So this year, I'm going to study English every day.","所以今年，我打算每天学英语。"],
["","I'm going to learn ten new words and read one lesson aloud.","我打算每天学十个新单词，大声朗读一课。"],
["","It won't be easy, but I believe in myself.","这不会容易，但我相信自己。"],
["","Little by little, one day I will speak English with confidence.","一点一点地，总有一天我会自信地说英语。"],
  ],
  words: [["forgotten","/fərˈɡɑːtn/","v. 忘记（forget 的过去分词）"],["often","/ˈɔːfn/","adv. 经常"],["foreign","/ˈfɔːrən/","adj. 外国的"],["aloud","/əˈlaʊd/","adv. 大声地"],["believe","/bɪˈliːv/","v. 相信"],["little by little","/ˌlɪtl baɪ ˈlɪtl/","一点一点地"],["confidence","/ˈkɑːnfɪdəns/","n. 自信"]] },

{ level: 2, title: "The interview", cn: "面试", point: "if 条件句：If + 一般现在时, … will + 动词。If you're honest, they will like you.",
  lines: [
["","Jenny had a job interview at a big company in London.","珍妮在伦敦一家大公司有个面试。"],
["","The night before, she couldn't sleep.","前一天晚上，她睡不着。"],
["","\"If I make a mistake, they won't hire me,\" she thought.","她想：「如果我犯错，他们就不会录用我。」"],
["","Her friend told her, \"If you're honest, they will like you.\"","她朋友对她说：「如果你真诚，他们会喜欢你的。」"],
["","In the interview, the manager asked a difficult question.","面试中，经理问了一个难题。"],
["","Jenny didn't know the answer, so she said, \"I'm not sure, but I'd love to learn.\"","珍妮不知道答案，于是她说：「我不确定，但我很愿意学习。」"],
["","The manager smiled.","经理笑了。"],
["","A week later, Jenny got the job.","一周后，珍妮得到了这份工作。"],
  ],
  words: [["interview","/ˈɪntərvjuː/","n. 面试"],["mistake","/mɪˈsteɪk/","n. 错误"],["hire","/ˈhaɪər/","v. 雇用"],["honest","/ˈɑːnɪst/","adj. 诚实的"],["difficult","/ˈdɪfɪkəlt/","adj. 困难的"],["question","/ˈkwestʃən/","n. 问题"],["later","/ˈleɪtər/","adv. 之后"]] },

{ level: 2, title: "An expensive taxi", cn: "一趟昂贵的出租车", point: "感叹句：What + a/an + 形容词 + 名词！What an expensive lesson! 也可以用 How + 形容词！How expensive!",
  lines: [
["","When I arrived in a new city late at night, I took a taxi to my hotel.","一天深夜我到了一个新城市，打车去酒店。"],
["","The driver didn't use the meter.","司机没有打表。"],
["","\"It's a fixed price,\" he said.","他说：「这是固定价格。」"],
["","I was tired, so I didn't argue.","我很累，就没有争辩。"],
["","The ride took only ten minutes, but he asked for eighty dollars!","车程只有十分钟，他却要八十美元！"],
["","The next morning, the hotel receptionist told me the normal fare was fifteen dollars.","第二天早上，酒店前台告诉我正常车费是十五美元。"],
["","What an expensive lesson!","多么昂贵的一课！"],
["","Now I always ask the price before I get in.","现在我上车前总会先问价格。"],
  ],
  words: [["meter","/ˈmiːtər/","n. 计价器"],["fixed","/fɪkst/","adj. 固定的"],["argue","/ˈɑːrɡjuː/","v. 争辩"],["ride","/raɪd/","n. 乘车"],["normal","/ˈnɔːrml/","adj. 正常的"],["fare","/fer/","n. 车费"],["lesson","/ˈlesn/","n. 教训；课"]] },

{ level: 2, title: "Working from home", cn: "在家办公", point: "There was / There were 表示过去「有」：There was no commute. There were too many distractions.",
  lines: [
["","Last year, my company let us work from home on Fridays.","去年，我们公司允许周五在家办公。"],
["","At first, I loved it.","一开始，我很喜欢。"],
["","There was no commute, and I could wear my pajamas all day.","不用通勤，还能整天穿睡衣。"],
["","But soon I found some problems.","但很快我发现了一些问题。"],
["","There were too many distractions at home: my cat, the TV, and the fridge.","家里让人分心的东西太多了：我的猫、电视，还有冰箱。"],
["","I also missed chatting with my colleagues.","我也想念和同事聊天。"],
["","Now I work in a café on Fridays.","现在我周五去咖啡馆工作。"],
["","It's quiet, the coffee is good, and there are no cats!","那里很安静，咖啡很好喝，而且没有猫！"],
  ],
  words: [["let","/let/","v. 让；允许"],["at first","/ət ˈfɜːrst/","起初"],["commute","/kəˈmjuːt/","n. 通勤"],["pajamas","/pəˈdʒɑːməz/","n. 睡衣"],["soon","/suːn/","adv. 很快"],["distraction","/dɪˈstrækʃn/","n. 让人分心的事"],["missed","/mɪst/","v. 想念（miss 的过去式）"]] },

{ level: 2, title: "A thank-you email", cn: "一封感谢邮件", point: "商务邮件常用句：Thank you for …（感谢……）；Please let me know if …（如果……请告诉我）；I look forward to …（期待……）。",
  lines: [
["","Dear Mr. Brown,","亲爱的布朗先生："],
["","Thank you for meeting with our team yesterday.","感谢您昨天与我们团队会面。"],
["","We really enjoyed learning about your new product.","我们非常高兴了解到贵公司的新产品。"],
["","As we discussed, we will send you a proposal by Friday.","按照我们讨论的，我们会在周五前给您发送方案。"],
["","It will include our ideas, the media plan, and the budget.","方案将包括我们的创意、媒体投放计划和预算。"],
["","Please let me know if you have any questions.","如有任何问题，请告诉我。"],
["","I look forward to working with you.","期待与您合作。"],
["","Best regards, Anna","此致，安娜"],
  ],
  words: [["dear","/dɪr/","adj. 亲爱的（信件开头）"],["enjoy","/ɪnˈdʒɔɪ/","v. 享受；喜欢"],["product","/ˈprɑːdʌkt/","n. 产品"],["discuss","/dɪˈskʌs/","v. 讨论"],["proposal","/prəˈpoʊzl/","n. 方案"],["include","/ɪnˈkluːd/","v. 包括"],["look forward to","/lʊk ˈfɔːrwərd tu/","期待"]] },
];
